### ISSUE TITLE
Multiple unknown items

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#100]
After the last merge there are now many unknown items including:  Stone walls, mese lamp microslab, flint&steel, enchanted pickaxe. There could be more.

**Comment by Lymkwi** [comment]
> flint&steel

That'll be fixed by myself since we agreed to let it in xdecor instead of removing it.

> mese lamp microslab

Only mese lamp microslabs? That's maybe my condition to make mese sawable which failed again, I'll check it.

> enchanted pickaxe

The mod was updated, I have no idea if there are any aliases in place.

> Stone walls

I have no idea what those are, but if they're from xdecor, it was upgraded recently, and again, there's retrocompatibility lasting for one or two versions until it's removed...

**Comment by BetterToAutomateTheWorld** [comment]
@kilbith Can you explain us why don't you configure aliases ?

**Comment by kilbith** [comment]
Les murs en pierre sont maintenant dans minetest_game, les alias sont ici : https://github.com/kilbith/xdecor/blob/master/nodes.lua#L478

Les microslabs de meselamp ont déjà été aliasé sur votre serveur : https://github.com/MinetestForFun/server-minetestforfun-skyblock/blob/d902654cfb989b0340e0176d6dfd957945f5abc4/mods/xdecor/workbench.lua#L263

Flint-and-Steel est maintenant dans minetest_game, l'alias est ici : https://github.com/kilbith/xdecor/blob/master/craftitems.lua#L24

Et pour les pioches enchantées : aucune idée, j'ai pas changé leurs noms récemment.

**Comment by aerozoic** [comment]
> I have no idea what those are, but if they're from xdecor, it was upgraded recently, and again, there's retrocompatibility lasting for one or two versions until it's removed...

Sorry it is actually called cobble wall, and yes from xdecor.

> Only mese lamp microslabs? That's maybe my condition to make mese sawable which failed again, I'll check it.

Just checked, it's actually all cuts of mese lamp.

**Comment by BetterToAutomateTheWorld** [comment]
~~Les murs en pierre sont maintenant dans minetest_game, les alias sont ici : https://github.com/kilbith/xdecor/blob/master/nodes.lua#L478~~ => Quelqu'un pour rajouter ces lignes au SB_game ou au xdecor ou au fichier misc/aliases SVP ? https://github.com/kilbith/xdecor/commit/4fc0cb1687b517379ad79d1b910dba0e4174db09

~~Les microslabs de meselamp ont déjà été aliasé sur votre serveur : https://github.com/MinetestForFun/server-minetestforfun-skyblock/blob/d902654cfb989b0340e0176d6dfd957945f5abc4/mods/xdecor/workbench.lua#L263~~ => Ne fonctionne pas

~~Flint-and-Steel est maintenant dans minetest_game, l'alias est ici : https://github.com/kilbith/xdecor/blob/master/craftitems.lua#L24~~ => Quelqu'un pour rajouter ces lignes au SB_game ou au xdecor ou au fichier misc/aliases SVP ?

~~Et pour les pioches enchantées : aucune idée, j'ai pas changé leurs noms récemment.~~ => Aucune solution pour l'instant

Quelqu'un peut s'en charger en urgence pour le prochain merge SVP ? @crabman77 @LeMagnesium 

Merci @kilbith pour ton retour :)
Laisse moi tout de même te dire que c'est la "catastrophe/merde" d'avoir enlevés tes aliases car tu les a mis dans MT_Game :/ (tu as pensé aux gens utilisant ton mod avec un MT_Game à jour mais pas aux gens utilisant ton mod avec un ancien MT_Game ou sans MT_Game...)

**Comment by kilbith** [comment]
Il me semble que @LeMagnesium avait modifié le code du Work Bench pour inclure les micronodes de meselamp mais sans modifier les alias plus bas. Ça a du produire un truc bizarre.

En général j'essaie de notifier tous les admins pour mettre à jour aussi vite que possible pour effectuer les changements, et quand la majorité d'entre eux l'ont fait, j'enlève les alias (en général après 1 ou 2 mois).

**Comment by BetterToAutomateTheWorld** [comment]
up

**Comment by Lymkwi** [comment]
On a pas fire, pourquoi mettre le flint and steel?

**Comment by BetterToAutomateTheWorld** [comment]
parce que utilisé par le chaudron, autant mettre fire

**Comment by kilbith** [comment]
Pour info, l'eau du chaudron bout avec n'importe quel node qui contient `fire` dans son nom. Donc le feu du mod `fire` n'est pas obligatoire.

**Comment by Lymkwi** [comment]
> parce que utilisé par le chaudron, autant mettre fire

J'ai recodé rapidement pour que ça fonctionne avec les torches, et @kilbith l'a bien rapellé, il suffit d'avoir du xdecor:fire ou tout ce qui contient "fire" et voilà.

**Comment by ghost** [comment]
Mais il n'y a pas de xdecor:fire c'est justement ça le problème https://github.com/MinetestForFun/server-minetestforfun-skyblock/blob/master/mods/xdecor/nodes.lua#L307
Et le fire:basic_flame ne tient pas longtemps, juste quelques secondes, après le chaudron ne bout plus, en plus on ne peut pas le poser partout, seulement sur des nodes flammable.

**Comment by BetterToAutomateTheWorld** [comment]
D'accord, donc si je comrpend bien le mod xdecor devient à la fois dépendant du "default" flint & steel mais aussi de fire... A moins de réécrire ça dans un de nos mod de façon "moche"...

En gros il nous faut de l'update depuis le default, l'ajout de fire ne me pose personnellement pas de problème, la propagation du feu sera désactivé, tout comme pour les autres serveurs

**Comment by Lymkwi** [comment]
> En gros il nous faut de l'update depuis le default

J'ai déjà mis à jour default.

> l'ajout de fire ne me pose personnellement pas de problème, la propagation du feu sera désactivé, tout comme pour les autres serveurs

Nous n'avons pas besoin de fire, **j'ai spécifiquement ajouté les torches comme déclencheurs pour ne pas avoir à le mettre juste pour allumer un chaudron**. J'ai même amputé le flint&steel de ses fonctionnalités pour ne pas dépendre de fire.

**Comment by BetterToAutomateTheWorld** [comment]
Mg, on en avait déjà parlé il y a un petit moment il me semble : il est préférable de garder le déclencheur par défaut du chaudron, le fait d'ajouter la torche est une bonne chose, néanmoins ce n'est qu'un "bonus"

**Comment by BetterToAutomateTheWorld** [comment]
Ok, suite aux dernières modifs de @crabman77 que je remercie pour son travail

tout est fonctionnel, je ferme le ticket.

**Comment by aerozoic** [comment]
My enchanted pickaxe is still an unknown item. 

Also i still can't make new enchanted tools with the enchantment table. I didn't make this a separate issue because i figured it is related.

**Comment by ghost** [comment]
@cessna151 it's fixed  https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/e504d33dd3be432748bde93f4c0637159cdff4b9
@kilbith un petit souci avec un "return" mal placé.

**Comment by kilbith** [comment]
https://github.com/kilbith/xdecor/commit/fa0d47380c96ce3cb06084484f665ca8fe977d84

N.B.: pensez à mettre à jour, j'ai rajouté des trucs sympas sur la table d'enchantement.

**Comment by BetterToAutomateTheWorld** [comment]
Ok, it's fixed, i closed the issue again, i will merge today the server
