### ISSUE TITLE
Add "moderator" as a prohibited player name?

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#101]
Somebody just logged in as the player name Moderator and is claiming to be a moderator.

**Comment by BetterToAutomateTheWorld** [comment]
Done in the mod : 
https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/d5c78bb0843120b988425e73cabd32deac99f78d
https://github.com/MinetestForFun/server-minetestforfun/commit/f038ec8284139389196f589f4d3efe0579bd5c0c
https://github.com/MinetestForFun/server-minetestforfun-hungry_games/commit/f89853680174d6d989c6dc1cd301ff14d70e9b33
https://github.com/MinetestForFun/server-minetestforfun-creative/commit/03c6b4530c98bb8f3ef48d0a45b7c2632c553df4

**Comment by BetterToAutomateTheWorld** [comment]
And on the text file, just in case :
https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/ca1e60c25ca3a15d664e5a2b47594469d570cd71
https://github.com/MinetestForFun/server-minetestforfun/commit/2f7b90ed02cfaeb3300a3eaa3930bbc48b81f896
https://github.com/MinetestForFun/server-minetestforfun-hungry_games/commit/f3d0c90d05604f2fd482a52e05c3c35f64ad7287
https://github.com/MinetestForFun/server-minetestforfun-creative/commit/f7e86c681753928f62e5a499ca5905442005f5d6

**Comment by BetterToAutomateTheWorld** [comment]
Everything is ok now :)
