### ISSUE TITLE
Fences/cobble walls are solid blocks

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#102]
Both fences and cobble walls are now showing as solid blocks.

**Comment by ghost** [comment]
It's actual mt game don't work on 0.4.13-stable, same issue on classic, work fine on actual version of git (future 0.0.14).

**Comment by BetterToAutomateTheWorld** [comment]
The 0.4.14-stable is coming, our servers will be upgraded at this moment https://forum.minetest.net/viewtopic.php?f=18&t=14102

**Comment by aerozoic** [comment]
Fences are fixed but Cobble walls are still blocks.

**Comment by aerozoic** [comment]
~~maybe i need to update to 4.14?~~

~~EDIT: 4.14 has not been officially released yet. I'm confused.~~

**Comment by BetterToAutomateTheWorld** [comment]
Yes we reverted the code for fences for the moment
The latest fences code will be re-implemented when we will upgrade to 0.4.14-stable

We will look after what's wrong with Cobble walls
https://github.com/MinetestForFun/server-minetestforfun-skyblock/blob/ec944dbd6a5c322ad708f669aaaf1a1af4b4949e/mods/xdecor/nodes.lua#L478

**Comment by Lymkwi** [comment]
For the record :

Cobble walls in latest 0.4.13-dev :
![](https://lut.im/oZi4KPoVBo/CLLCcCbTe8CTTiC1)

Cobble walls in 0.4.13-stable :
![](https://lut.im/w61CCM4ycS/aaVZpPUwPTUZqziV)

Note: The walls mod was directly copied from MTGame.
Question: What black magic technology does this mod use?!

**Comment by BetterToAutomateTheWorld** [comment]
Wow, that's weird that I think...

Again a good idea to add features in dev version and use it instantly on latest stable subgame like MT_Game and latest stable mods like xdecor in this case...

It totally break servers on the latest stable Minetest version... Nobody will use a dev version of Minetest Server if he wants something stable on production for his players.

Well, the 0.4.14-stable in coming soon...

**Comment by BetterToAutomateTheWorld** [comment]
Solved since @crabman77 revert the fences code. 
Closed this issue

**Comment by BetterToAutomateTheWorld** [comment]
fences : OK
walls : NOK

**Comment by BetterToAutomateTheWorld** [comment]
@crabman77 
We are now on a 0.4.14-stable version, can you do the changes to fix the fences & walls please ?

**Comment by aerozoic** [comment]
Walls are still not fixed.
:large_orange_diamond:

**Comment by ghost** [comment]
Walls are added only in 4.0.14, there are no old uggly code.
![walls](https://cloud.githubusercontent.com/assets/7189389/15654994/169ad572-2699-11e6-8546-1301b1896599.jpg)

**Comment by aerozoic** [comment]
Sorry, i just realized, my old cobble wall was automatically converted to "default:cobble"

It's fixed now
 :large_orange_diamond:
