### ISSUE TITLE
A new skin for players

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-skyblock#103]
Somebody ask this skin for the skin choose panel :
http://www.minecraftskins.com/skin/4152042/redstone-suit/

Have we enough space in the player skin panel for this new skin ?

Please, I need comments and opinions !

**Comment by aerozoic** [comment]
Looks like just another skin to me. Did somebody important request it? If not, i wouldn't waste my time adding it. The whole idea was to have a minimal number of skins. There were several skins i would like to have kept but i didn't in order to keep the skin count low and balanced (male/female/fantasy). 

This is just my opinion :sunglasses: 

:large_orange_diamond:

**Comment by Lymkwi** [comment]
That's just another skin, indeed... Though it is a reference to Guy Fawkes.
We could add it, the problem is that we do not know its license nor its creator.

**Comment by BetterToAutomateTheWorld** [comment]
Have a Guy Fawkes skin please to me
Maybe we can redo it ?
If the MT skin database haven't already this kind of skin we can send this new skin to them

**Comment by BetterToAutomateTheWorld** [comment]
Assigned to @cessna151, seems you want to do it :)

**Comment by aerozoic** [comment]
I think if we do this we should also add one more female skin, i've had many requests for another female skin as well.

**Comment by BetterToAutomateTheWorld** [comment]
Ok, i think it's a good idea

**Comment by aerozoic** [comment]
from http://www.minecraftskins.com/terms-and-conditions/

> 1. Use License
> 
> Permission is granted to temporarily download one copy of the materials (information or software) on MinecraftSkins.com's web site for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title, and under this license you may not:
>         **modify or copy the materials;**
>         use the materials for any commercial purpose, or for any public display (commercial or non-commercial);
>         attempt to decompile or reverse engineer any software contained on MinecraftSkins.com's web site;
>         remove any copyright or other proprietary notations from the materials; or
>        **transfer the materials to another person or "mirror" the materials on any other server.**
>     This license shall automatically terminate if you violate any of these restrictions and may be terminated by MinecraftSkins.com at any time. Upon terminating your viewing of these materials or upon the termination of this license, you must destroy any downloaded materials in your possession whether in electronic or printed format.

**Comment by aerozoic** [comment]
This one is similar: http://minetest.fensta.bplaced.net/#name=Kirby%20In%20A%20Suit

**Comment by BetterToAutomateTheWorld** [comment]
If we remade it, no problem

Yes, except the head, it's the same suit :)

**Comment by aerozoic** [comment]
I've added a guy fawkes skin of my own creation and a female skin from the database: 6b9a0fb7890572b3654b33a911516e656905af2e

They still need previews which @LeMagnesium said he would write a script for that.

:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
Perfect, i will merge them when the previews will be pushed :)

**Comment by Lymkwi** [comment]
Is this issue solved yet? The preview was pushed yesterday.

**Comment by BetterToAutomateTheWorld** [comment]
I will merge tomorrow or Saturday.
I think you can close the issue, everything is good in my point of view, and in the worst case, we can re-open this issue.

**Comment by aerozoic** [comment]
I pushed two skins, but you only did a preview for one skin.

:large_orange_diamond:

**Comment by Lymkwi** [comment]
@cessna151 : For you information :

```
./generate_skin_preview.py <path_to_skin_file>
```

**Comment by BetterToAutomateTheWorld** [comment]
Preview now generated
