### ISSUE TITLE
Feature request : Hunger system

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-skyblock#104]
Some players ask me for hunger system.

In fact we have the farming mod so some fruits/vegetables are spawning in the sky world and players drops many apple without a real use with them...

Please, I need comments and opinions !

**Comment by aerozoic** [comment]
I've only experienced the hunger system on minecraft. Does it work the same on Minetest? Assuming it's nearly the same... With the lack of animal mobs, we would be relying solely on farming. I imagine this might be difficult for new players. Especially being trapped on their island for awhile. Although maybe the hunger system could be modified to be very slow and/or limited to only reducing health to 50% or some other preset limit? Also maybe there could be food rewards added to the level 1-4 quests?

If i'm not mistaken, farming quests are being implemented in level 4&5? It would make more sense to have a hunger system if that is the case.

:large_orange_diamond:

**Comment by Lymkwi** [comment]
> Some players ask me for hunger system.

I would agree, on the only condition that this hunger system is very slow to increase hunger and only drops health points down to 1. A hunger system would justify adding farming items like hoes or such in level 4, as well as seeds. We could fill that level using them.

**Comment by BetterToAutomateTheWorld** [comment]
@cessna151 
The Minetest hunger system can be like Minecraft but the main difference with Minetest is we can tweak it like we want
For the food, remember the first quest you did in level 1 was digging trees, i re-new an account the last day and i reached 40 apples in my first 5 minutes ingame...

@LeMagnesium 
I agree with you, it's better for newbies if this system don't kill players but just reduce they life to 1 or 2 (0.5 ou 1 red hearth), it will punish them if they fall down :)

---

And of course i was wondering of a simple hunger system, no lag issues, no crash issues, and the hunger bar need to decrease slowly, our main goal isn't to do a "boring" system, but a "simple & easy" system :)

**Comment by Lymkwi** [comment]
> "simple & easy" system :)

I think the original hunger mods should fit our purposes. I'm gonna see how well maintained it is as of now.

**Comment by BetterToAutomateTheWorld** [comment]
I think also the original hunger system should be good (but slower than the original and with the 1 or 2 hearth(s) minimum if the player is hungry)

**Comment by BetterToAutomateTheWorld** [comment]
Done and merged
