### ISSUE TITLE
sethome and usebug possible

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-skyblock#105]
The report inbox was useful today, someone introduce to us a possible usebug with sethome :

> If you penetrate one time an other player home and do a "/sethome" with the "/home" command you will can be teleported forever in the other player house

We can fix it easily if we add a condition to the /sethome (not be near a protector which isn't with our name)

_(thanks to vegito for this report)_

**Comment by Lymkwi** [comment]
I like the idea of restricting home positions; I'll code that as fast as possible.

**Comment by aerozoic** [comment]
Testing locally i can still /sethome in protected areas.

EDIT: Every account i log into locally has full privs and /revoke doesn't work for some reason :/

**Comment by BetterToAutomateTheWorld** [comment]
@cessna151 because you're connected with the admin account (with "server" privilege)

The @LeMagnesium fix is well coded in my point of view :)

**Comment by Lymkwi** [comment]
> Testing locally i can still /sethome in protected areas.

Locally you have 'server admin' privileges and can bypass any area protection, that's why you're still able to do that.

**Comment by aerozoic** [comment]
Yes i know that, how do i disable server admin privs?

**Comment by BetterToAutomateTheWorld** [comment]
I think you can't with the GUI, you need to open two Minetest windows.

With the first window, create a server, and connect you to this server, with the nickname "admin" for example, you can reduce this window
With the second window, connect you as "cessna" to your local server (127.0.0.1:30000 if default port), and this window/account will be a normal player without admin privs :)

**Comment by Lymkwi** [comment]
> Yes i know that, how do i disable server admin privs?

You can't. Use a second local account which doesn't have them by default (meaning its name isn't in the 'name' configuration field). Mine is usually "Hydrogen" or another chemical element.

**Comment by BetterToAutomateTheWorld** [comment]
I closed this issue, it's solved.
