### ISSUE TITLE
Add PVP features

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-skyblock#107]
This days, many players ask us for a PVP system, we will include it but i think, in a way it will be acceptable for everyone, let me explain our roadmap :
#### Swords
- ~~Add swords, with linear increase damage with the ore you use to craft them https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/62ada47b38c38c0314408fe2b17216c7a5b97d83~~
- ~~We will add them with modified textures from our "MFF_subgame", this default textures are 32px, well done and beautiful https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/62ada47b38c38c0314408fe2b17216c7a5b97d83~~
#### Armors
- ~~Add armors, with linear increase damage with the ore you use to craft them (3d_armor) https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/d92b6925cb4d24dde3ba284553fd986bf9686ffd~~
#### The PVP Button
- ~~Add the "PVP_button" mod (https://forum.minetest.net/viewtopic.php?f=9&t=13137&hilit=pvp) https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/34917f15ebc9f8fb73ef79f91f509adde903bfac~~
- ~~Tweak/recode the mod to be compatible with "u_skins" inventory https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/34917f15ebc9f8fb73ef79f91f509adde903bfac~~
- ~~Also we will add a button in your inventory to activate or deactivate PVP (default sword/shield are great) https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/34917f15ebc9f8fb73ef79f91f509adde903bfac~~
- ~~We need to set a cooldown for this activate/deactivate feature, 5 minutes for the beginning https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/0df504d999e672eef08d9b9a2f530755b2e36749~~
#### Let's battle !
- ~~At last, activate damage and PVP on the server~~
- ~~The spawn are will be a "safe area", no PVP even if players are "PVP enable" https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/387b51150a427aee90988e836d78bae938ef73f5 https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/af8213bebb6ed5b3565ccedf6b3c102bac376324~~

_(if you have other ideas with this way of thinking, do not hesitate and tell us here)_

**Comment by Lymkwi** [comment]
I think PvP will add a bit of spice in the Skyblock recipe, and swords could be crafted in Level 4 for quests.

> Add swords, with linear increase damage with the ore you use to craft them.

I uncommented the swords; you're usually the one who balances their damages, but I'll copy those from Classic. For now I won't push that modification.

> - Add the "PVP_button" mod (https://forum.minetest.net/viewtopic.php?f=9&t=13137&hilit=pvp)
> - Tweak/recode the mod to be compatible with "u_skins" inventory.
> - Also we will add a button in your inventory to activate or deactivate PVP. (the texture for this button should be 2 crossed swords, or 2 swords don't crossed for activate/deactivate PVP in my point of view)
> - We need to set a countdown for this activate/deactivate feature, well let's try 5 minutes for the beginning.

Done. There was already the texture of a sword for the PvP button. I left it as is, we can change that later. I like the idea of a cooldown for that button, because otherwise it's not really interesting, if you can switch really fast and enable it only at convenient moments. However, there shouldn't be a lot of time to wait for before toggling PvP, so I would rather go with 2.5 minutes (which is already a long time during sword fights).
The mod will not be enabled until you add `enable_pvp = true` to the configuration file.

**Comment by aerozoic** [comment]
Yes, i talked to several people a few days ago and they all said PVP is the reason they like the "other" skyblock server better.

Just to make sure i understand... If somebody is not interested in pvp all they need to do is leave the pvp button deactivated and that person can never be damaged by others or cause damage to others?

:large_orange_diamond:

**Comment by Lymkwi** [comment]
> Just to make sure i understand... If somebody is not interested in pvp all they need to do is leave the pvp button deactivated and that person can never be damaged by others or cause damage to others?

That's exactly it.

**Comment by aerozoic** [comment]
Perhaps make the spawn area a safe zone?

Add armor too?

Maybe a short cooldown timer after a TP request is accepted?

:large_orange_diamond:

**Comment by cessna151** [comment]
What about armor?

**Comment by cessna151** [comment]
Maybe have a cooldown timer after a TP request is accepted?

**Comment by BetterToAutomateTheWorld** [comment]
@LeMagnesium 
The MFF_Classic sword damages should be great, good initiative.
For the sword/shield textures for activate/deactivate button, i see them and it's good like this for me :)
I push for the 5 minutes idea, it's the minimal time for me to do a balanced PVP system. Imagine a player with PVP is killed by a player without PVP but who activated PVP only for killing with surprise the first PVP player, 5 minutes is a minimal amount of time for letting the first player find an kill again the second player.

@cessna151 
We can indeed make the spawn area safe, and it's a good idea ! => @LeMagnesium can you do this ?
Armors will be a good addition, but later, we need to add PVP and swords in a first merge, and correct the problems we will meet with them.
Why do you want a shorter PVP button cooldown when /tpy is used ?

**Comment by aerozoic** [comment]
If players ~~have already waited the 5 minutes and they are active PVP, then they~~ do a TP request, some players might be caught off guard especially since i don't think most players pay attention to whether it was a TPR or a TPHR request. A ~10 second PVP delay would give both players an equal chance in my opinion. ~~I was under the impression after the 5 minute cooldown a player could TP and instantly start fighting, maybe i misunderstood,~~ does a TP request reset the 5 minute cooldown?

**Comment by Lymkwi** [comment]
> does a TP request reset the 5 minute cooldown? 

It doesn't. There is no way to reset an action timer, at least none was added to our code (there is one but we never use it). You can only wait until 5 minutes elapse.

**Comment by aerozoic** [comment]
I totally misunderstood the cooldown (i thought the cooldown meant you had to wait 5 minutes before PVP activates when PVP is pressed). My original idea still applies though, a 5-10 second delay would allow both players to prepare and have an equal chance. As of now, victory would likely go to the player who orients the quickest after the TPR is accepted.

**Comment by aerozoic** [comment]
The PVP button doesn't change to a shield.

**Comment by BetterToAutomateTheWorld** [comment]
Yes it see it also, didn't know why, maybe a problem with u_skin integration ?

**Comment by BetterToAutomateTheWorld** [comment]
Done and merged.
