### ISSUE TITLE
[xban2] Gui does not wordwrap

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#109]
The xban gui doesn't wordwrap so i can't see the entire ban report for a player. All i can see is the time and date, which is actually the CURRENT server time. Is this normal? Does it show the ban time and expire time?

![clipboard01](https://cloud.githubusercontent.com/assets/15715378/14856283/78331338-0c65-11e6-952f-6c57026a04a2.jpg)

**Comment by BetterToAutomateTheWorld** [comment]
Don't know if we can fix it without redo the entire formspec... 
Clearly a "xban" bad feature
Maybe @crabman77 can help us ?

linked @kaeza just in case he wants to fix his mod :)

**Comment by kaeza** [comment]
@Ombridride Thank you for linking. The xban2 GUI needs some love. Expect something soon(tm).

**Comment by kaeza** [comment]
@cessna151 We have no way to know the client's timezone (it's actually possible, but out of scope for xban2), so the server time is the best we can do.

**Comment by aerozoic** [comment]
The server time is fine. But maybe i didn't explain well... it is showing live current time, if i keep clicking my name in the list i can watch the seconds tick by. It would be nice to know the time the ban was issued and the expire time. I can't see the end of the message, maybe this info is already there but at the end where i can't see it?

**Comment by BetterToAutomateTheWorld** [comment]
An other problem is we can't read more than ~80 letters, it cuts our full ban message

**Comment by Lymkwi** [comment]
> An other problem is we can't read more than ~80 letters, it cuts our full ban message

I'm not sure you can have a ban reason longer than 80 characters.

**Comment by BetterToAutomateTheWorld** [comment]
@LeMagnesium look at the screenshot, in the ban message, near 60-65 characters are taken by the date/hour :)

**Comment by kaeza** [comment]
See minetest-mods/xban2@974b47f8f6f9f654e9ce3e0c2cb92e45ce743bcf.

![screenshot_20160505_075050](https://cloud.githubusercontent.com/assets/2388420/15042049/0ad7e4b6-1297-11e6-90ed-fb03331b29be.jpg)

**Comment by BetterToAutomateTheWorld** [comment]
It's a good step, thank you for your work @kaeza :)
@LeMagnesium can you update the subtree please ?

**Comment by Lymkwi** [comment]
https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/af10e1164288bec00fa52135b06e74081cfd6db6

This seemingly helps for the issue. Thanks @kaeza .
Should we close it or try to adapt the GUI to Sb a little bit more?

**Comment by BetterToAutomateTheWorld** [comment]
I think we can't do more with the GUI, i closed this issue.

Thank you again @kaeza !

**Comment by kaeza** [comment]
@Ombridride, @LeMagnesium, You are quite welcome.
