### ISSUE TITLE
Health/armors hudbar problems

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-skyblock#112]
![health_armor](http://i.imgur.com/7HYtt2y.png)
- The both hudbars lines are grey (like always enough, but it's not !)
- The armor bar is our health bar ! (inverted with the real health bar)
- So, the armor bar is regenerating, not the health bar, and when the armor bar reach 0, you die !

**Comment by Lymkwi** [comment]
Apparently the double health bar issues disappeared on its own.
https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/ddb9ce30a5650947935b6f8b0e8a81749e373142
