### ISSUE TITLE
[u_inv] Crafting guide is all messed up

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#113]
Some items have no recipe while others show many incorrect recipes yet other items are missing completely.

Examples: 
- The default sign is missing from the craft guide. 
- Signs, tools, and ore don't have a recipe.
- Cobble shows 16 recipes.
- Wood planks show 40 recipes.

Thanks LizzardBeth for the report.

:large_orange_diamond:

**Comment by Lymkwi** [comment]
Are we talking about XDecor's craft guide or u_inv's one?
EDIT: Also, this doesn't pose a threat to the server so I put it average

**Comment by BetterToAutomateTheWorld** [comment]
Thank you for the report @cessna151 
- The default sign is missing from the craft guide => need to fix it
- Signs, tools, and ore don't have a recipe => need to fix it
- ~~Cobble shows 16 recipes => normal~~
- ~~Wood planks show 40 recipes =>normal~~

You also need to answer @LeMagnesium question, but i think we need to check on all craft guides

**Comment by aerozoic** [comment]
I'm referring to u_inv's crafting guide.

@Ombridride 
It's not normal to show 40 recipes for wood planks. It should only show one which is the default wood for that type of plank (pine, jungle, or regular).

:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
@cessna151 Then, I need to see ingame the craft recipes to understand the problem.. :)

**Comment by aerozoic** [comment]
This has been mysteriously fixed. Any idea which commit fixed it?

**Comment by BetterToAutomateTheWorld** [comment]
All of the problems has been fixed or just one ?

**Comment by aerozoic** [comment]
Everything seems fixed. I can't find anything wrong with the crafting guide now.

:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
Well, i closed the issue :p
(Maybe it was an xdecor update)
