### ISSUE TITLE
incorrect reference to inventory armor preview texture

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#114]
All enchanted armor causes the lua error "failed to load image..." when it is placed in the armor slot in the armor tab of inventory. The reference is to enchanted armor preview texture, but it should reference the normal armor preview texture.

Also, i don't know if this is a separate or related issue... Only one enchanted piece of armor is allowed to be placed in the armor slots at one time.

:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
@kilbith can you light us about this issue ?

**Comment by Lymkwi** [comment]
> kilbith can you light us about this issue ?

It's not his fault. 3d_armor's way of determining a piece of armor's texture name is based on the idea that all pieces' textures' name are composed of the piece's item name, so even when xdecor sets the inventory_image as the original piece's inventory image, the preview file loaded still doesn't exist for 3d_armor.

**Comment by aerozoic** [comment]
The second part of this issue was never addressed but i think was reported again here: https://github.com/MinetestForFun/server-minetestforfun-skyblock/issues/118

:large_orange_diamond:
