### ISSUE TITLE
Eating doesn't repair health

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#115]
Eating doesn't repair health even with full hunger.

Edit: This was tested locally with latest updates.

:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
The health isn't regenerating instantly but 1 half hearth by 1 half hearth when you're feed

The instant health regeneration is more easy to understand for you ? We can do it

**Comment by aerozoic** [comment]
Let me be more specific. Yes when hunger bar is full, the health bar slowly regenerates but i can't continue eating to make the health regenerate faster like it used to be before hunger was added. Maybe this is the way it is supposed to be?

:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
Yes it's the way it's supposed to be... 
Can you answer me, is it good for you, or you think it's not very understandable for players ?

**Comment by aerozoic** [comment]
I think it's understandable. I was just used to the old way. It would be nice though if it could work both ways... If I could choose to let full hunger bar slowly regenerate health or i could choose to keep eating to fully restore health faster.

**Comment by Lymkwi** [comment]
> It would be nice though if it could work both ways..

I'm gonna see if it's not too much of a pain in the A to implement that, and maybe it will be added.

**Comment by BetterToAutomateTheWorld** [comment]
@LeMagnesium not the both ways ! it's a too high amont of life regenerate !
Let's just make all foods restore instantly the amount of life. It's clearly the easier way to understand hwo it works for new players. ;)

**Comment by BetterToAutomateTheWorld** [comment]
Done.
