### ISSUE TITLE
[ignore] doesn't work if player uses /me

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#117]
If a player is added to ignore list and then that player uses `/me <text>`, it can be seen although normal chat from this player is hidden.

:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
@LeMagnesium can you check this issue please ?

**Comment by Lymkwi** [comment]
> If a player is added to ignore list and then that player uses /me <text>, it can be seen although normal chat from this player is hidden.

`/me` is not normal chat. I will need to hack the `me` chatcommand. It should be feasible, but as ugly as what I've already done.

**Comment by Lymkwi** [comment]
https://github.com/MinetestForFun/ignore/commit/2bc3665479d2c875f509eac4643e218b7990c926
