### ISSUE TITLE
armor bug

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/server-minetestforfun-skyblock#118]
From IRC:
<brothersome> Bug! Cannot put enhanced armor back from my inventory to the box

**Comment by BetterToAutomateTheWorld** [comment]
Linked @sofar (or @kilbith ?) if it's not already reported

**Comment by sofar** [comment]
I have no idea what this is about. If there is a bug, please report it to the mod or project and don't @ include me in mff threads, I already have too many notifications from github that are not actionable.

**Comment by Lymkwi** [comment]
If by 'the box' you meant the armor inventory then it works fine for me.
Also why the F\* would you @ sofar? He's not involved here, 3d_armor isn't originally in Skyblock

**Comment by BetterToAutomateTheWorld** [comment]
Sofar, we often link Kilbith like that without problems, but ok we won't link you again in the future. We will probably not open always issues on the mod repository...

@LeMagnesium 
Calm down, you're really not up to date :) https://forum.minetest.net/viewtopic.php?f=3&t=14556

**Comment by aerozoic** [comment]
Could this be the same as what i reported in #114?

> Only one enchanted piece of armor is allowed to be placed in the armor slots at one time.

:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
Yes, I think it's the same issue, and the server hasn't been merged before the @LeMagnesium fix.

Well, I closed this issue, if it happens again, do not hesitate to re-open this issue.

**Comment by aerozoic** [comment]
Testing locally the armor tab still only allows one enchanted item.

:large_orange_diamond:

**Comment by Lymkwi** [comment]
Well, when looking for the piece's type, 3d_armor uses the second part of the item's name, and for enchanted items, it's always "enchanted", so it thinks there is already a similar piece in the inventory.
I'm gonna fix that.
