### ISSUE TITLE
Shields can't be enchanted

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#119]
Shields are not allowed to be put into the enchantment slot. Maybe this is normal?

:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
Shields aren't maybe part of the enchantment table ?

**Comment by BetterToAutomateTheWorld** [comment]
Xdecor is made like this, you can't enhance shields :
https://github.com/minetest-mods/xdecor/blob/fa0d47380c96ce3cb06084484f665ca8fe977d84/enchanting.lua#L44

But, you can craft wood/cactus shield enhanted with an addition of a steel_ingot in the craft recipe.

We won't tweak the xdecor mod to implement this feature, it you want them, create an issue in xdecor repository : https://github.com/minetest-mods/xdecor/issues
