### ISSUE TITLE
Signs

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-skyblock#12]
maybe add the sign_lib mod ?

Maybe takes the default sign texture/inventory texture from the our MFF repository, the actual texture are very ugly (minetest 0.4.10 or older...)

**Comment by Lymkwi** [comment]
If we add sign_lib I need to update the game. I'll do it later.

**Comment by BetterToAutomateTheWorld** [comment]
We can add the sign_lib in the same way we added it to the Hunger_gmes server, just the mod without the modpack, where is the problem ?

**Comment by Lymkwi** [comment]
https://github.com/cornernote/minetest-skyblock/issues/44

**Comment by BetterToAutomateTheWorld** [comment]
Oww.. Ok, need to fixed this issue before add this mod :)

Anyway, we can changed the default signs textures until this issue is fixed...

**Comment by BetterToAutomateTheWorld** [comment]
You forgot the default signs textures tweaks

**Comment by BetterToAutomateTheWorld** [comment]
You forgot the default signs textures tweaks
