### ISSUE TITLE
[Update] protector

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-skyblock#120]
Only on Skyblock server

https://github.com/tenplus1/protector

BE CAREFUL To keep our changes !

I think the last commit we need is https://github.com/tenplus1/protector/commit/f02fe24b6138f5beb08ad88cacc0c884c2bd6c60

**Comment by Lymkwi** [comment]
I did my best. Hopefully nothing is broken (I tested, but I can't be 100% sure).

**Comment by Lymkwi** [comment]
https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/98b580e6bf4619a945950256f0d0b232d185368c

**Comment by aerozoic** [comment]
Is there an easy way to see the commit that actually shows the changes?
:large_orange_diamond:

**Comment by ElementW** [comment]
@cessna151 https://github.com/MinetestForFun/protector/commit/bafa30026de4d198baac00126d9f1e03b965b5d8

**Comment by aerozoic** [comment]
Thanks but i'm lookin for an easy way to find it so i can do it myself in the future.
:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
@cessna151 
If you want to see all commits for a specified mod you can :
1. Github project repository
2. Navigate to the file you want to see (in our case protector, but it's a submodule, it's outside of our SB repository, but anyway, if you click on the mods folder, you will be redirected to the submodule repository) https://github.com/MinetestForFun/protector/tree/master
3. Select the file you want to see the history, for example init.lua https://github.com/MinetestForFun/protector/blob/master/init.lua
4. You can now click the "history" button, you will now see all of our commits about this mod
5. You can also click the "blame" button for more details, to see all the file modifications per user per commit

**Comment by aerozoic** [comment]
I don't think i've explained my question very well.... I would like to know if there is a way to see which commits were included in the update when i see this "+Subproject commit bafa30026de4d198baac00126d9f1e03b965b5d8"? I understand that this brings the submodule up to date but what i can't figure out is how to see which commits were applied to this particular update and which commits were already applied.
:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
Like I said : 

==> You can also click the "blame" button for more details, to see all the file modifications per user per commit 

https://github.com/MinetestForFun/protector/blame/master/init.lua
![](http://i.imgur.com/A1cdkvX.png)
