### ISSUE TITLE
[travelnet] Elevator malfunction

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#122]
After an elevator network is setup, when a station is selected, it teleports to the wrong station. For instance, i set up a network of 10 elevators and no matter which station i'm at or which station i select, it will always take me to station 3 or 4. It seems random. On another network it would always take me to station 10 or 11.

EDIT: This only seems to be an issue with new networks. My existing networks don't seem effected.

Thanks ihatedrift for the report.

:large_orange_diamond:

**Comment by Lymkwi** [comment]
Is the issue fixed by digging/replacing all elevators?

**Comment by aerozoic** [comment]
Dig them all first and then place them all or dig and replace each elevator one at a time?
:large_orange_diamond:

**Comment by Lymkwi** [comment]
Either one, you could try the two of them, and if only one works, or none, then we have an idea of where the issue is.

**Comment by aerozoic** [comment]
Alrighty, i will hopefully test that sometime today.
:large_orange_diamond:

**Comment by aerozoic** [comment]
I can't replicate the issue anymore. I'll reopen if it happens again. Perhaps MT4.14 fixed it for us.
:large_orange_diamond:
