### ISSUE TITLE
[skyblock_levels] placing a sign doesn't work!

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#125]
Placing a sign for the level 1 quest does not trigger the quest as completed which prevents new players from getting past level 1.

:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
@LeMagnesium @crabman77 you already fix this, but i didn't remember how ? (it's probably the sign_lib update which broke the quest)

**WARNING : please comment this kind of code expressively**

**Comment by aerozoic** [comment]
Yes this quest was working until the update today. I also think it was the sign_lib update which broke the quest. Perhaps "default_sign == default:sign_wall_wood"?
:large_orange_diamond:

**Comment by ghost** [comment]
Fixed https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/3bb579c759f97c005b7ec3f8fefe82b2531e3d58

**Comment by BetterToAutomateTheWorld** [comment]
Merged and works well. thank you for the fix.
