### ISSUE TITLE
Armour models/skins problem

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-skyblock#126]
When you're wearing an armour, you can't see it with F7 and other players didn't see it :
![](http://i.imgur.com/NpqHEQm.png)
![](http://i.imgur.com/18WLvXr.png)

**Comment by ghost** [comment]
Fixed https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/0b5333bd78f256e33b6a4266c4d41cb4e7d04377
