### ISSUE TITLE
Suggestion - Hide "quest completed" messages for other players

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#129]
I think it would be better if quest completed messages were hidden from other players chat so only that player would see his completed quest message. Or perhaps just hide level 1 quests? What are everyone else's thoughts?
:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
This feature was made on purpose

If i remember well, actually the "small" quests(steps to level) aren't shown for everybody but only for the player which complete the "small" quests
And the "big" quests(level completed) are shown for everyone

Can you confirm it's the actual features ?

So, you want to hide the "big" quest(level completed) for level 1 ?

Im right ?

**Comment by aerozoic** [comment]
No. Every single quest completed for every level for every player shows in the main chat for all players to see. This is alot of spam now that the server is getting popular. Hiding only the level 1 quests would reduce this significantly, however; hiding all level quests would be ok too.
:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
I agree with you, when 20+ players are connected it can be a lot of spam source

The "small" quest notifications can be hidden for everyone, just displayed for the player which complete the quest, it's just a line to comment, i will check/do it when i've time

**Comment by BetterToAutomateTheWorld** [comment]
Done
https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/e32b35751f729d06ba7f5e1cfa5575378133d3ff

@LeMagnesium 
Can you confirm it's good and close the issue ? I can see in the git-history you wrote this lines :)

**Comment by aerozoic** [comment]
Quest completed msgs no longer show in main chat, but they also do **not** show in chat for the player doing the quest. However, level completed quests show in chat like normal.
:large_orange_diamond:

**Comment by aerozoic** [comment]
fixed: 2d5baebba25867b437936349557f0be7693f5dab

@LeMagnesium did i fix it correctly?
:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
Oh yes you're right, it's _minetest.chat_send_all_ for messages to everyone...

**Comment by Lymkwi** [comment]
https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/94a670a3c2a2dd143ba925d718c69dd9b29af058

Can we close?
