### ISSUE TITLE
xdecor rope and protected areas

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-skyblock#131]
rope from xdecor mod can be stollen/grieffen in protected areas, need to fix it 
![](http://i.imgur.com/PNiAkaP.png)

**Comment by ghost** [comment]
fixed https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/ca24f961703a45dc9ef9cb1406731875c9e29716

**Comment by BetterToAutomateTheWorld** [comment]
Thank you :)
