### ISSUE TITLE
[Windows] Texture warnings during server connect...

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#132]
I get these warnings every time i connect to the server. According to my debug file it started happening February 16th. And there are exactly 20 lines each time i join the server

```
2016-06-07 19:25:38: ACTION[main]: Irrlicht: Performance warning, slow unlock of non power of 2 texture.
2016-06-07 19:25:38: ACTION[main]: Irrlicht: Performance warning, slow unlock of non power of 2 texture.
2016-06-07 19:25:38: ACTION[main]: Irrlicht: Performance warning, slow unlock of non power of 2 texture.
2016-06-07 19:25:38: ACTION[main]: Irrlicht: Performance warning, slow unlock of non power of 2 texture.
2016-06-07 19:25:38: ACTION[main]: Irrlicht: Performance warning, slow unlock of non power of 2 texture.

```

:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
http://irrlicht.sourceforge.net/forum/viewtopic.php?f=1&t=9558

Apparently, we need to found the textures which aren't multiple of 2

**Comment by ghost** [comment]
This ? -> http://zerobin.qbuissondebon.info/?3a6d26af38de173b#ttDCv8a/6ifsz3F+OdDJeU3jgeL78kdXWT4Cpv87xd8=

**Comment by Lymkwi** [comment]
We can't simply multiply everything by two, can we? That would be so heavy in terms of data...

**Comment by BetterToAutomateTheWorld** [comment]
It's the easy way to do it yes, but it's unfortunately not the best way to do it...

**Comment by Lymkwi** [comment]
I haven't seen those warnings yet. What version of Irrlicht are you using @crabman77 ?
If it is only Irrlicht freaking out in your terminal, we should let it be...

**Comment by aerozoic** [comment]
To clarify, when i start minetest, two windows open, the first window just shows a log of what the game is doing, the second window is the actual game. It is in the first window where i see these warnings.
:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
Yes, cessna is on windows

**Comment by Lymkwi** [comment]
> Yes, cessna is on windows

Whatever system cessna is on, it comes from Irrlicht. If irrlicht complains about some textures being heavy or having dimensions which are not a power of two, then we should also see it on Linux/BSD/Whatever.
So how can we fix this?

**Comment by Darcidride** [comment]
@ObaniGemini don't you want to do this issue ? I didn't see any commit, tell us informed please :)

**Comment by BetterToAutomateTheWorld** [comment]
@ObaniGemini Didn't you want this issue ? I didn't see any commit(s), keep us informed please :)

**Comment by ghost** [comment]
irrlicht with "Burningvideo" driver don't like textures non power of 2.

http://zerobin.qbuissondebon.info/?aa465bdc45058914#R0fxcC7LiIVFzRFNZjRvrF2rJlFX7Pqa9fYI8ZsCBok=

**Comment by aerozoic** [comment]
Is this issue resolved, can we close it?
:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
We need ot ask to ingame player, especially when there are just connected to check if the warning message continue to be displayed

**Comment by aerozoic** [comment]
I don't see it anymore on windows or linux.
🔶

**Comment by BetterToAutomateTheWorld** [comment]
Ok, let's close it  for now, maybe we will reopened it if needed.
