### ISSUE TITLE
the /who command floods chat

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#139]
A few months ago using /who provided i nice list of players separated by a comma. Now it floods the chat with each player on a new line.
:large_orange_diamond:

**Comment by Lymkwi** [comment]
Is it the IRC chat command you are talking about?
Nevermind, I found it. I'm gonna do an interface for that thing.

**Comment by Lymkwi** [comment]
https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/8c2b26d096897939bbf60c98497c3c30e1d02941

**Comment by aerozoic** [comment]
@LeMagnesium Would it be easy to add a close button?
:large_orange_diamond:
