### ISSUE TITLE
Bee hives no longer make honey.

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#140]
LizzardBeth reported that bee hives no longer make honey. Apparently this has been broken for awhile.
:large_orange_diamond:

**Comment by ghost** [comment]
Honey is only created between the daytime 5AM to 6PM (when sunlight) and the _xdecor:artificial_beehive_ must be **near 3 flowers minimum**. The _Artificial Beehive_ can store until 16 honey
