### ISSUE TITLE
Round-down doesn't persist

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#141]
When round-down is sprayed it gets rid of the plants but then they just come back during normal regrowth ABM's.
:large_orange_diamond:

**Comment by Lymkwi** [comment]
Damn typos in commit messages https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/982fcbf2f4f441f709bcdb04673598eb2f401b57
