### ISSUE TITLE
Re-add the "max button"

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-skyblock#142]
Some players want the "max button" feature re-implemented. 

In fact it was a very good feature, we need to fix it / recode it :)

**Comment by Lymkwi** [comment]
MineTest's API still doesn't give us the required methods and mechanisms to implement it properly, I cannot do any better than last time.

**Comment by Lymkwi** [comment]
How is it? Are you satisfied with the current implementation?

**Comment by BetterToAutomateTheWorld** [comment]
ok, let's see this bug issue about max_button https://github.com/MinetestForFun/server-minetestforfun-skyblock/issues/158
i close this issue for duplicated
