### ISSUE TITLE
**Please disable MAX button and merge ASAP**

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#145]
The MAX button is still bugged. It's Causing invalid items in inventory. Same old bugs that it used to have. IIRC it also causes server crashes.

:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
Done, need to see with @LeMagnesium what's hapenned

**Comment by Lymkwi** [comment]
Updated, junk fixed, it works now.

**Comment by BetterToAutomateTheWorld** [comment]
Perfect, thank you.
