### ISSUE TITLE
I lost kick/ban privs.

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#146]
My kick/ban privs have mysteriously been lost. Have i been fired from moderating? :P

:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
Of course not, you're a team member ! I will chek your privs when i've time :)

**Comment by aerozoic** [comment]
fixed
:large_orange_diamond:

**Comment by Lymkwi** [comment]
Err, it seems that I lost them as well. I think everyone who had privileges other than the default ones (including fly&fast) lost them a while ago.

**Comment by aerozoic** [comment]
I'm also curious what caused this to happen? I also had the irc_admin priv which Mg should probably have too.

:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
Surely the same problem as the players with fly/flast in the level 5 ... but we haven't a way to re-add them without an hard nickname in code for moderators...

**Comment by Lymkwi** [comment]
Everything is fine as of now for me and @cessna151 . Did anyone else lose privileges they want to get back or should we close?

**Comment by BetterToAutomateTheWorld** [comment]
i think we can close this issue.
