### ISSUE TITLE
Players die when logging in.

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#147]
I've got several reports of players always starting at 0,0,0 and dying when they join the server. I have this problem as well. It has been this way for a couple days.

:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
Strange, we need to investigate

Linked @LeMagnesium and @crabman77

**Comment by Lymkwi** [comment]
It happens sometimes that a player's client doesn't receive their coordinates in time, it's rare, but it shouldn't happen often. I'm gonna have to check the code.
Update: there is no bit of code to teleport at 0,0,0; I suspect it to be a client error. Could anyone build something at 0,0,0?

**Comment by aerozoic** [comment]
More info... All players that join start at 0,0,0 immediately after login but are then normally teleported to their spawn/last location before falling to the bottom. For some reason this teleport is sometimes delayed long enough for the players to touch the bottom causing the death. (The last couple days this has been far more often than normal)

I was sitting near 0,0,0 for awhile to observe this.

Also @LeMagnesium I have built a pad below 0,0,0 so that players won't touch the bottom anymore. We'll see what happens.
:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
I think it's due to our recent lag server side because of more than 30 players online very often...

**Comment by aerozoic** [comment]
My pad at 0,0,0 works! I just joined and fell onto the pad for several seconds, then was teleported to my last location. No more player death on joining :-)

EDIT: I also waited and observed other players falling onto the pad. 
:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
perfect, thank you for the fix :p

It proove it's a lag client side related issue.
