### ISSUE TITLE
life & farming_redo

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-skyblock#148]
the farming foods don't restore life, just satiation

**Comment by Lymkwi** [comment]
It seems all food restore life, they just don't fully restore it.
https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/6f53b4c30907b5b4c5582b9776ecfff573358636~~
~~At least, until now.~~
Hang on... @Darcidride, do you really want all farming food to restore full life?
~~Nevermind, I just tested online, and it doesn't work. WTF?!~~
EDIT3:
- [X] Tomato : 3 unit
- [X] Potato : 1 unit
- [X] Bread : 20 units
- [X] Corn : 3 unit
- [X] Raspberries : 1 unit
- [X] Blueberries : 1 unit
- [X] Watermelon : 2 units
- [X] Baked potato : 5 units
- [X] Green beans : 2 units
- [X] Carrots : 3 units
- [X] Golden Carrots : 10 units
- [X] Bar of dark chocolate : 3 units
- [X] Coffee : 2 units
- [X] Cookies : 2 units
- [X] Corn on the Cob : 5 units
- [X] Cucumber : 3 units
- [X] Chocolate Donuts : 3 units
- [X] Graps : 2 units
- [X] Blueberries Muffin : 4 units
- [X] Pumpkin bread : 7 units
- [X] Raspberry Smoothie : 2 units

They work. ALL of them. On Cyber's server, on your server, and locally as well.

**Comment by BetterToAutomateTheWorld** [comment]
We don't want all food to restore full life. Just the amount they do, but instantly, you did the right thing. Thank you for your work
