### ISSUE TITLE
Level 5 and loosing privileges

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-skyblock#149]
Many players complain about they privileges loosing at the level 5, I have a workaround :
5sec after the player connection : if level 5 is completed then add "fly / fast" privilege to the player.

With this workaround, if a player loose its privilege, when he will disconenct/reconenct, we will hae agian its privilege back

**Comment by BetterToAutomateTheWorld** [comment]
j'ai fait ça vite fait avec les quelques infos que j'ai pu glaner de l'APIi minetest/skyblock et du LUA :

```
-- A rentrer quelque part dans le level 5
minetest.register_on_joinplayer(function(player) -- à la conexion du joueur
        local max_level_privs = core.get_player_privs(player_name)
        privs['fly'] = true
        privs['fast'] = true}) -- check les deux privs fly & fast

        local name = player:get_player_name() -- on recupère le nom du joueur

    if max_level_privs then
        minetest.after(5, tick, name) -- wait 5sec
        print("You have the fly & fast privilege and it's normal.") -- si oui print OK
    else
        minetest.after(5, tick, name) -- wait 5sec
        core.set_player_privs(player_name, privs) -- donne les privs
        minetest.chat_send_player(player_name, "For a mysterious reason, you don't have the fly & fast privilege, we gave them to you again.")   -- si non print NOk mais on ta refilé
    end
end)
```

Quelqu'un peut vérifier svp ? (surement à corriger) @LeMagnesium @crabman77

**Comment by Lymkwi** [comment]
Ça n'a aucun sens de patcher tant qu'on ne sait pas d'où ça vient, on ne sait même pas si c'est une erreur du code Lua lui-même.
Je vais aller retrouver mes privileges, et si je les perds, on regardera les logs.

**Comment by BetterToAutomateTheWorld** [comment]
https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/1c32e67a2590301026a44729a110705e0869063f
