### ISSUE TITLE
Add the gauges mod ?

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-skyblock#15]
Maybe we need to add the gauges mod ? Is PVP possible in skyblock ?

**Comment by Lymkwi** [comment]
PvP is possible, but not important at all.

**Comment by ObaniGemini** [comment]
Shouldn't we disable PvP ? There's already a grieffing possibility, I think we shall remove the killing possibility. If some people want to fight, they can go on MFF, MFF-HG, or every other server that allows PvP. Skyblock is a building game, not a fighting game.

**Comment by BetterToAutomateTheWorld** [comment]
I agreed with @ObaniGemini i can see in-game many players kill each other, that's not the goal of the SkyBlock subgame.

I can add, we need to removed the sword craft / code / textures because they will be useless.

You can see the only 3 iteration of the "sword" word in the entire subgame here : 
![3_only_sword_word_in_the_subgame](http://i.imgur.com/unydxvE.png)

So, we need to disable the punch_players for all players by default and for the actual created players. (like the protected "spawn tower" area in MFF, but at a world area)

**Comment by Lymkwi** [comment]
If we disable punch_players, then we don't need to remove code, that would be better for merges.
I will add the peace_areas mod.

**Comment by ObaniGemini** [comment]
But it will still light and simplify subgame if we remove those parts :) .

**Comment by BetterToAutomateTheWorld** [comment]
I think we don't need _peace area_ code or any mod, we just need a line in the minetest.conf, we need to check the minetest.conf.example  ;)

**Comment by Lymkwi** [comment]
There is a line called `disable_pvp` but it's only a flag for servers.minetest.net. As far as I know, as long as `enable_damages` is true, player punches will damage each other.

**Comment by Lymkwi** [comment]
https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/12a3b13212e0b51a3ac243787394b660663a3ceb
https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/9822e0b72c366cce29823f793dc5cfb894ca7f62

**Comment by BetterToAutomateTheWorld** [comment]
Great, we can closed this issue now, thank you !
