### ISSUE TITLE
Max Lag results

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#150]
| Server Time | Players | Max Lag |
| :-: | :-: | :-: |
| 2016-07-09 17:29 | 36 | 5.9 |
| 2016-07-09 19:27 | 30 | 3.5 |
| 2016-07-09 19:48 | 35 | 4.6 |
| 2016-07-09 20:07 | 35 | 9.5 |
| 2016-07-09 23:33 | 23 | 4.3 |
| 2016-07-10 00:47 | 26 | 27.5 |
| 2016-07-10 00:51 | 23 | 21.2 |
| 2016-07-10 03:36 | 20 | 6.2 |
| 2016-07-10 05:03 | 17 | 2.8 |
| 2016-07-10 15:39 | 15 | 7.3 |
| 2016-07-10 16:20 | 17 | 21.1 |
| 2016-07-10 17:07 | 28 | 8.0 |
| 2016-07-10 18:12 | 39 | 4.9 |
| 2016-07-10 18:33 | 41 | 4.8 |
| 2016-07-10 19:36 | 41 | 4.0 |
| 2016-07-10 19:52 | 36 | 11.2 |
| 2016-07-10 20:14 | 14 | 8.7 |

:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
Thank you @cessna151 
Ok, I connected a few times when the lag was over 7 seconds with more than 20 ingame players and try to dig/put a node. 
The result was an instant node dig & put.

So the max_lag concerned only some players with a really weird connection and isn't server side... 

However, I didn't try with more than 40 ingame players, we absolutly need to try with our "good" connection if the fig/put is instant or not.

**Comment by aerozoic** [comment]
Digging and placing is not when you notice the lag. You really notice the lag when you try to open a chest and place objects in it or take them out and also when you press the Go home and spawn buttons (/home, /spawn) or /inbox. I have this problem all the time now.

EDIT: Also try placing 10 blocks very fast and watch the stack count. It doesn't update like it should.

:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
I tried with some blocks, the explanation is simple, too many players are building(putting nodes) at the same time and the database queue the requests, we use the faster backend we can use for Minetest, but with 30+ builders at the same time, the REDIS database can't handle them all without queuing them... 

Let's say it's a Minetest engine optimization problem, not a mod problem...

I closed the issue.

**Comment by Lymkwi** [comment]
I'm just gonna add 'core-related' then.
