### ISSUE TITLE
Server 'flooded' with bots, potential attackers

### ISSUE THREAD

**Issue by Lymkwi** [MinetestForFun/server-minetestforfun-skyblock#151]
- A filter has been put in place -> @ElementW cannot access the server any more, thus, he's unable to apply our modification
- Multiple servers have seen the same events happen
- The accounts `sadie[0-9]+` are connecting at an impressive speed
- Some persons state that their accounts were unavailable after a server was stormed by Sadies. Nobody has been able to confirm for now.

Todo: 
- [x] Apply the modification
- ~~Get an idea of what/who is causing that to happen~~

**Comment by aerozoic** [comment]
~~@Ombridride I have xbanned several sadie***\* accounts. If you want i'll make a list.~~

EDIT: They are unbanned.
:large_orange_diamond:

**Comment by aerozoic** [comment]
I'm unbanning them, i just went to see a couple "sadie's" in game and they move around and build stuff.
:large_orange_diamond:

**Comment by Lymkwi** [comment]
It seems nothing harmful happened. We still have the pattern for those sadies up, but no need to ban.
Psychosis over. Issue closed.
