### ISSUE TITLE
Changes in accesses depending on levels

### ISSUE THREAD

**Issue by Lymkwi** [MinetestForFun/server-minetestforfun-skyblock#152]
The following changes have been requested and agreed upon :
- [X] Level 3 : Players are granted access to the skin customization menu
- [X] Level 4 : All players receive and keep fly and fast privileges
- [X] Level 5 : Players can fight with PVP

**Comment by BetterToAutomateTheWorld** [comment]
- [X] Add some explanations about this ^ in random_messages => https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/0658bfac53a5b5bd1163ffaf4a0168348dbde326

**Comment by Lymkwi** [comment]
https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/51f4cb96fce273c37efa3905271967f2326443e5
