### ISSUE TITLE
Playernames with only special characters can join

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#153]
For instance new players can join using just underscores and dashes.
:large_orange_diamond:

**Comment by aerozoic** [comment]
I didn't test which all special characters would work. Did you?
:large_orange_diamond:

**Comment by Lymkwi** [comment]
Technically speaking, only A-Za-z0-9-_ can be used, so I forbid the only two non alphanumeric ones
