### ISSUE TITLE
SERVER CRASH, NO REBOOT!

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#156]
@Darcidride The server has been down for hours.
:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
Damn, ok solved, i missed a crontab merge...

**Comment by Darcidride** [comment]
Reopened the issue for @LeMagnesium 

The Sadie regex doesn't work at all, Sadie*** continu to connecting to our server, the auth.txt fiel was corrupted because of a "Sadie***" account...
