### ISSUE TITLE
I lost all my privs (again)

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#157]
It has happened again. I only have basic privs. I think the real cause of this should be investigated. I think this is caused by the same issue that causes players to lose fly/fast which was [hotfixed](1c32e67a2590301026a44729a110705e0869063f) but never actually resolved.

More info if it helps... I did MFFSB-Bot, cmd privs from IRC and it was completely blank. But now after going in game it lists basics privs.
:large_orange_diamond:

**Comment by Lymkwi** [comment]
My theory is auth corruption. That explains the uncany tendency for privs to be reset and why your privileges were blank. It might be caused by a mod, but I've read almost every single line in Skyblock's code and none could do that in a normal situation.

**Comment by Lymkwi** [comment]
https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/cddbddaa048ca672d8162014ab8bb9dbf5f434f4

Until Auths are not in a database.

**Comment by BetterToAutomateTheWorld** [comment]
Thank you for this needed hardfix :)

**Comment by BetterToAutomateTheWorld** [comment]
Closed because hardfixed.
