### ISSUE TITLE
MAX button is broke

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#158]
Max button does nothing for all items. No errors or any actions at all.
:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
@LeMagnesium, can you fix it please ?

**Comment by BetterToAutomateTheWorld** [comment]
@LeMagnesium, up

**Comment by Lymkwi** [comment]
@cessna151 I'm so bitter right now, if you dropped me in a cup I'd taste like coffee.
https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/bbea065717a34605378eeab494dd7f0d1e02d61c

I will never touch that again, except for minor bug fixes. It better work as is though.
