### ISSUE TITLE
stack of buckets consumed when collecting water

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#159]
Just got a report from a player that when you have a stack of buckets and click on a water source, all but one of the buckets are consumed.
:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
This bug was fixed a long time ago by @LeMagnesium if my memory is good

Maybe @LeMagnesium can fix this again and add a clear comment to the code for the future ?

**Comment by BetterToAutomateTheWorld** [comment]
Fixed, thanks to @crabman77
