### ISSUE TITLE
Empty bucket not stackade anymore

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-skyblock#161]
![](http://i.imgur.com/uXLIux0.png)

They was stackable before... We tweak them for this feature

@LeMagnesium I think it was your improvment, can you redo it please ?

**Comment by ghost** [comment]
fixed

**Comment by aerozoic** [comment]
Already reported here: #159 
:large_orange_diamond:
