### ISSUE TITLE
All passwords have been reset for accounts older than a month!

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#163]
I have just verified ANY player that has not logged into the game for a month or longer has had there password reset! 
:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
ok, serious problem... We need a solution now...

**Comment by BetterToAutomateTheWorld** [comment]
Closed since now auth.txt in handle in a MariaDB database.

**Comment by aerozoic** [comment]
Were the passwords restored for old accounts?
:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
It was surely due to the corrupted auth.txt, they need to try again the connection on their account(s) and tell us if it works.
In my point of view, no reasons it still doesn't work

**Comment by aerozoic** [comment]
I just tested, passwords have not been restored. I was able to login to another old account.
:large_orange_diamond:

**Comment by aerozoic** [comment]
This still isn't fixed and many old accounts are being logged into. Some by accident by new players that don't know the account was already created and some by players who know about the bug.

Every single account that is logged into is forever lost to the original owner due to the new password entered.
:large_orange_diamond:

**Comment by aerozoic** [comment]
Does anybody know if this was a one time event or if passwords are continuing to be reset after a period of time roughly 30 days?
:large_orange_diamond:

**Comment by Lymkwi** [comment]
Mine was still there even after a few months of inactivity so I believe it was fixed.

**Comment by BetterToAutomateTheWorld** [comment]
I think it was a one time event due to the plaintext that handle in the past the passwords and maybe some of this file(s) was corrupted. Anyway, now it's in database (MariaDB), so no need to worry anymore :)

**Comment by aerozoic** [comment]
I just tried to log into some accounts that were 5 months old and couldn't so this was a one time event. However the issue still remains. I can still log into old accounts that existed when this issue occurred that haven't been accessed since.
:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
@aerozoic yes i know, and i think we can't do anything about it, just hoping players are reconnecting with their own password and don't see anything :/

**Comment by aerozoic** [comment]
I think we can close this in that case.
:large_orange_diamond:
