### ISSUE TITLE
Max button ignores a couple things...

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#167]
@LeMagnesium the max button seems to be working good as far as i can tell. It is ignoring a couple things however... Both dirt and clay blocks craft into clay lumps but max button doesn't work for either. It also doesn't work for crafting obsidian shards to sand. The max button simply has no action or errors for those items.
:large_orange_diamond:

**Comment by aerozoic** [comment]
Add diamond axe to the list.
:large_orange_diamond:

**Comment by Lymkwi** [comment]
Isn't fixed by now? All tools are handled separately, and I fixed that bit missing for 1-column-wide recipes.

**Comment by BetterToAutomateTheWorld** [comment]
@LeMagnesium i don't merge the server since 1~2 weeks, maybe your improvments aren't currently ingame, i will merge soon all servers + tags

**Comment by aerozoic** [comment]
Testing locally everything seems fixed except for the axe.
:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
Perfect, is this case i closed the issue, the server merge will come soon ;)

**Comment by aerozoic** [comment]
@Darcidride Why close the issue if it still doesn't work for the axe?
:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
oh yes sorry, I closed this issue too fast

**Comment by Lymkwi** [comment]
It's groups.
My code doesn't check for groups. I'm gonna fix that.
