### ISSUE TITLE
[xdecor] Mailbox glitch

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#169]
I can't reproduce this error but LizzardBeth sent this screenshot of her mailbox: 

![screenshot](https://lut.im/FKBAFEJTMf/169sqEGtnAf28h4w/.png)
:large_orange_diamond:

**Comment by Lymkwi** [comment]
Formspec f*ck-up, oddly enough, it happens, and like for HUD, it's very random..

**Comment by BetterToAutomateTheWorld** [comment]
Yes I agree with @LeMagnesium as long I remember,it's a random, ugly, and totally unfixable bug of Minetest...

**Comment by aerozoic** [comment]
LizzardBeth just informed me that this was solved by digging it and replacing it.
:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
Ok perfect :)
