### ISSUE TITLE
Log getting flooded when players fall to bottom

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#171]
When a player falls to the bottom and dies then does nothing, the log gets flooded with:

```
2016-08-28 22:34:42: ACTION[Server]: [skyblock] get_spawn() for Rex2328 is {x=12928,y=12928,z=20320}
2016-08-28 22:34:42: ACTION[Server]: [skyblock] skyblock.feats.reset_level(Rex2328)
2016-08-28 22:34:42: ACTION[Server]: [skyblock] skyblock.feats.update(Rex2328)
2016-08-28 22:34:42: ACTION[Server]: [skyblock] get_spawn() for Rex2328 is {x=12928,y=12928,z=20320}
2016-08-28 22:34:42: ERROR[Server]: mysql_auth: set_privileges(Rex2328) failed: affected row count is 0, expected 1
```

:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
yes, we met this issue on all servers with "death_messages" mod, maybe we can add a condition, only one death message per 10sec for example, @LeMagnesium can you give us your opinion ?

**Comment by Lymkwi** [comment]
@Darcidride The flood's a combination of skyblock debug and mysql_auth errors. death_messages have nothing to do with that.

**Comment by BetterToAutomateTheWorld** [comment]
I was talking about the ingame death_messages, sorry if i didn't be clear.

This logs messages can't be avoided and are needed. (for the initial post)

In the case of death_messages, it remember me an old bug that we can maybe correct

**Comment by aerozoic** [comment]
Maybe i've only noticed it because of the flood of new players recently, but i don't remember this happening in the past.
:large_orange_diamond:

**Comment by aerozoic** [comment]
@LeMagnesium and I discussed on IRC a mod that would automatically kick any player if their Y Pos<=-9 for 60 seconds.
:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
Not a bad idea, I will personally prefer a 10 to 20sec before kicking the player

**Comment by ghost** [comment]
fixed https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/f4453789bd1388bd6e1ee8eaec81d4f88c9fef03

**Comment by BetterToAutomateTheWorld** [comment]
Or this, good idea, thank you @crabman77
