### ISSUE TITLE
New player regulator mod

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#172]
Taken from #160 @LeMagnesium said: 

> @cessna151 and I discussed about a feature which could potentially prevent the flood of modifications made to auths.txt from corrupting our data. It is a mod which would record the join time of players and hold the timestamps in a table. After X minutes, any entry from a player would be removed. If the player left, their entry would be removed as well after a short period of time (~30 seconds, for example).
> The idea is to prevent new players from joining when too many entries are already in our array, and ask them to wait for the purge of enough entries to make place for theirs.

I think this would still be useful. I was sitting on the side of the map last night just watching the new accounts flood in. I'll bet we are getting 1000+ new accounts per day. This is causing the map to get HUGE.

It would be really great if a mod like this could distinguish between new accounts and existing ones so that existing player accounts could join unrestricted.
:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
We already discuss about this kind of mod, and we agreed to the conclusion : it's to difficult to code.

But why not discuss again about this mod, im open for it :)

**Comment by aerozoic** [comment]
Sorry, i was unaware of that conversation.
:large_orange_diamond:

**Comment by Lymkwi** [comment]
The fact that we had no disappearance of privileges, or passwords reset, or data lost, or auth file corrupted, since we started using mysql_auth, that tell me that coding that mod isn't exactly worth the effort at the moment (it shouldn't be especially hard to code).
