### ISSUE TITLE
maxbutton bug report

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-skyblock#173]
thepiercingarrow reports :

```
the max button allows me to stack items past the stack limit (99)
For example, i can get 1 stack of 99*4 planks by hitting the max button after putting in 99 trees
```

**Comment by aerozoic** [comment]
I don't think this is a bug. I like this feature very very much! If it ain't broke don't fix it! :)
:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
Ok, let's see what @LeMagnesium answer, maybe it can be stay like this

**Comment by Lymkwi** [comment]
"It's not a bug, it's a feature".

**Comment by BetterToAutomateTheWorld** [comment]
Ok, perfect :)
