### ISSUE TITLE
Ugly Pine Trees

### ISSUE THREAD

**Issue by mzhaodev** [MinetestForFun/server-minetestforfun-skyblock#175]
Occasionally, Pine Trees grow in a very ugly way:
<img width="711" alt="ugly_pine_trees" src="https://cloud.githubusercontent.com/assets/16855663/18218586/aa9c2338-7131-11e6-825b-9c7017bdf447.png">

**Comment by aerozoic** [comment]
It only seems to happen on tilled soil.
:large_orange_diamond:

**Comment by Lymkwi** [comment]
As far as I remember, the fact that their rotation axis is wrong has existed in minetest for years. It's a bug either somewhere in the engine or the rotation handling in Lua (builtin?).
I could try to investigate but that'd take a while.

**Comment by BetterToAutomateTheWorld** [comment]
In my point of view, it's a really low priority bug, no need to waste time on it for the moment. Anyway, if you want to investigate/fix it, have fun on it @LeMagnesium  :)

**Comment by aerozoic** [comment]
In my view if @LeMagnesium actually wants to work on this he can reopen the issue. Or if anyone thinks this shouldn't be closed they can reopen, otherwise it's closed.
:large_orange_diamond:
