### ISSUE TITLE
HUD armor icons

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#176]
![screenshot at 2016-09-08 21-50-19](https://cloud.githubusercontent.com/assets/15715378/18373116/6f3e4b6c-760f-11e6-8c25-3edfceae9f61.png)
:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
Curious, someone can try it ingame and give us a screenshot of the rendering ?

**Comment by Lymkwi** [comment]
![](https://lut.im/g3pDpwY4uQ/0WEZc5lWVXRYzMnQ)

With all diamond items strenghtened using the enchanting table.
I don't know how the calculation is done, I'll look that up.
