### ISSUE TITLE
Enchanted tools + max button = server crash

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#177]
If you put two enchanted tools in the craft grid to make one repaired tool and press max button... BOOM server crash. Normal tools don't do this.
:large_orange_diamond:

**Comment by Lymkwi** [comment]
Enchanted tools are somehow not registered; I have no way of ancitipating a toolrepair recipe.
I'll just ignore them.

**Comment by BetterToAutomateTheWorld** [comment]
THank you for this urgent fix @LeMagnesium
