### ISSUE TITLE
Item frames don't accept some food

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#179]
![screenshot at 2016-09-13 19-35-45](https://cloud.githubusercontent.com/assets/15715378/18495159/9a31f958-79e9-11e6-8659-dd785878714d.png)

This is a bug, i just found item frames currently on the server with food. 

The food that doesn't work is any that can be used as seeds. Other food like bread works fine.
:large_orange_diamond:

**Comment by ghost** [comment]
fixed https://github.com/MinetestForFun/server-minetestforfun-skyblock/issues/179
