### ISSUE TITLE
Add [random_messages] mod

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-skyblock#18]
We need to add the [random_messages] mod and to fill it with our usual inforamtions/tips (visit our website, etc...) AND we need to fill it with some useful tips/reminder specificly linked to the SkyBlock subgame 

(for example : explain to players if they fall they die, and if they die, they reset there level, it avoid many questions about possible bugs)

(example 2, this kind of information can also help a lot : Concernant l'actualisation des formspecs des quests, si tu déco/reco c'est ok.)

**Comment by Lymkwi** [comment]
https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/da453f26416235b8df104a6af2ec0f64c0298b5a

Modify as you wish.

**Comment by BetterToAutomateTheWorld** [comment]
https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/68cdc957f8444709789e8abeabd30f0f6ea6eae4
Great, need to fill it now :p

**Comment by BetterToAutomateTheWorld** [comment]
I added some random_messages.
Indeed, in-game players complained because they readed the same 3 random_messages all days...

You can correct the existing random_messages if you have a better translation, or you can add renadom_messages

Anyway, i closed this issue because the work is done. (mostly)
