### ISSUE TITLE
Request for new mods

### ISSUE THREAD

**Issue by halttheranger** [MinetestForFun/server-minetestforfun-skyblock#180]
https://github.com/halttheranger/luckyblock-modpack

**Comment by halttheranger** [comment]
the mod is a lucky block mod and buffer mods for it

**Comment by BetterToAutomateTheWorld** [comment]
Hi @halttheranger 

Thank you for your issue, we will discuss between us if add your mod or not.

We will inform you soon on this issue

**Comment by Lymkwi** [comment]
I don't think there is anything especially worth being added.. The modpack is nice, but there are way too many new tools, and items to incorporate that could create conflicts (xdecor's enchanted tabels) with no real interest other than adding content to an already bloated subgame.
Your work's nice, and it's clear that it took time to do, but it's too much to add for no real benefit on the player's experience.
