### ISSUE TITLE
Strange problem with signs

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#182]
YuGiOhJCJ has reported that his signs, located at (11949,-4,20159), have had the text disappear 3 times. Each time is a few days apart. He has about 25 signs with this problem. Changing the text on the signs has no effect. The only way to resolve it is to dig and replace the sign. Replacing that many signs would be a huge PITA as you could imagine. This last time he left the signs blank so you can see the problem for yourself.
:large_orange_diamond:

**Comment by YuGiOhJCJ** [comment]
I often see this message in the console: "2016-09-16 13:39:56: ERROR[Main]: Client::handleCommand_ActiveObjectMessages: caught SerializationError: deSerializeString: couldn't read all chars". Maybe it is related to this bug. Anyway if you need a screenshot, here it is: 
<img src="http://yugiohjcj.free.fr/minetest-sign-1.png">

**Comment by Lymkwi** [comment]
I'd say that's an issue in the engine with the creation of the floating text entities. I don't even know what could cause it , maybe an unhandled charset for the text, which is BS. There is no applicable fix I can think of except normalizing the text to ASCII and forcing a respawn. I'm gonna investigate on that.

**Comment by BetterToAutomateTheWorld** [comment]
Surely an unhandled charset in the sign text, yes. (Engine problem)
UTF-8 should be in Minetest since a long time...

**Comment by aerozoic** [comment]
Just to be clear he has many other signs in this same area that don't have this problem. Only some of them do this. And the text written is just normal text, nothing special.
:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
Hi,

For information, I digged a sign and putted it again, then i rewrite the initial text on it and it was fixed : 
![sign_bugfix](http://i.imgur.com/2rZt7ZB.png)

If I remember well the sign_lib code, a /clearobjects will do exactly the same thing to all signs.

I will /clearobjects soon, i didn't do it since a really long time

(UPDATE : Finally, i did and ingame warning message and /clearobjects now, I will check again the sign problem at the end of the clearobjects)

**Comment by YuGiOhJCJ** [comment]
The sign you fixed has a strange position of the text on my screen: <img src="http://yugiohjcj.free.fr/minetest-sign-2.png">

**Comment by BetterToAutomateTheWorld** [comment]
The clearobjects can't be ended due to the amount of time needed... after 30min it wasn't over...

I reduce the onground living time of items to reduce the next clearobjects, I need to planned it.

For the problem of the above screenshot, it's a knew problem, and you don't have any other solution than dig/put again the sign, sorry ...

**Comment by YuGiOhJCJ** [comment]
Crazy! The problem happened again on new signs I have just placed today:
<img src="http://yugiohjcj.free.fr/minetest-sign-3.png">
Is it possible that there are too much signs at the same place and maybe there is a limit?

**Comment by BetterToAutomateTheWorld** [comment]
It's funny, because when I come ingame and try to put text on your signs, it works...
(I dig, put again, and write text)

**Comment by YuGiOhJCJ** [comment]
Yes, that's exactly the behavior I have too :\

**Comment by Lymkwi** [comment]
@Darcidride and @YuGiOhJCJ : what characer encoding standards do your system use?

**Comment by YuGiOhJCJ** [comment]
My system is using the UTF-8 character encoding:

```
$ locale
LANG=en_US.utf8
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE=en_US.utf8
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=
```

**Comment by aerozoic** [comment]
I've recently noticed random signs all over the map have lost there text even though hovering on them shows the text.
:large_orange_diamond:

**Comment by YuGiOhJCJ** [comment]
I have a new information to give about this issue.
Just before the text disappears completely on the sign, the text is in a state where it is not yet completely invisible.
It is invisible when the camera rotation is in a specific angle.
It means that moving the view from left to right and right to left makes the text appears and disappears progressively.
See here the result:
<img src="http://yugiohjcj.free.fr/minetest-sign-4.png">
<img src="http://yugiohjcj.free.fr/minetest-sign-5.png">

**Comment by Lymkwi** [comment]
Could you give us the coordinates of one bugged sign please? I'm gonna try something with a local copy of the map.

**Comment by YuGiOhJCJ** [comment]
Yes, the sign you see on the last screenshot is located at coordinates: (11936.0, -5.5, 20159.6).

**Comment by YuGiOhJCJ** [comment]
On wooden signs placed on the floor, it seems that it happens only if the text is facing South and West.
See my screenshots:
<img src="http://yugiohjcj.free.fr/minetest-sign-n.png" />
<img src="http://yugiohjcj.free.fr/minetest-sign-s.png" />
<img src="http://yugiohjcj.free.fr/minetest-sign-w.png" />
<img src="http://yugiohjcj.free.fr/minetest-sign-e.png" />

**Comment by aerozoic** [comment]
I'm still finding new signs all over the map with this problem. Has it been confirmed that this is a minetest issue?
:large_orange_diamond:

**Comment by YuGiOhJCJ** [comment]
It is an issue with the signs_lib mod: https://github.com/minetest-mods/signs_lib/issues/2

**Comment by aerozoic** [comment]
Since this isn't an issue with Skyblock i am closing the issue and we can reference the issue mentioned above for updates.
:large_orange_diamond:
