### ISSUE TITLE
Default Unisex skin before the u_skin privilege

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-skyblock#185]
I received this request from dman :
<dman> hey do you think you could change the starter skin to a unisex one so it's more fair for females who join and have to wait till they get a skin to represent them although you may need to download another skin I do think it would be  good idea on this server

I think this request makes sense, we need to put a default unisex skin, now we need to choose one ;)

**Comment by Lymkwi** [comment]
Sam, the default skin, was conceived to be matchable to both male and female (even its name can match both). Could we add it back as default?

**Comment by BetterToAutomateTheWorld** [comment]
In my point of view, Sam isn't well designed for an "unisex skin", for me it's clearly a male skin, and he is too common, I think we should choose an another unisex skin :)

**Comment by Lymkwi** [comment]
The most gender-neutral skin I could find in our database is this one, from Classic. Would it fit?
![genderneutralskin](https://cloud.githubusercontent.com/assets/6785985/18967585/1010522a-8686-11e6-9a1d-c2c49cbd91b6.png)

**Comment by Lymkwi** [comment]
@Darcidride Should I push that one purple skin? I haven't found any other skin.

**Comment by BetterToAutomateTheWorld** [comment]
@LeMagnesium 
Yes, i think you can push it :)

**Comment by aerozoic** [comment]
Did i miss something or should this be closed?
:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
Yes, you're right, im going to close now the issue, thank you
