### ISSUE TITLE
delprotect/protection_bypass toggle doesn't work

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#186]
@LeMagnesium I don't remember were we stand on this issue and you're never on IRC anymore so i'm putting this here :)
:large_orange_diamond:

**Comment by aerozoic** [comment]
To clarify for others... I requested a simple toggle so that while i have those two privs i can easily turn them off so i don't accidentally build into somebody else's protected area.

Initial commit: https://github.com/MinetestForFun/protector/commit/8f3037f5636c56754a229f58ed8d78212974b91c
And first fix attempt: https://github.com/MinetestForFun/protector/commit/4bd02fb3f8c759fd56f0202022f8a9e73b11ddda

:large_orange_diamond:

**Comment by ghost** [comment]
fixed https://github.com/MinetestForFun/protector/commit/b903eb8923dc69f055dac9f869ad5c109ccd7109
and https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/d652fb8c1fc5b784c825fb13a278c053f5e36a45

**Comment by aerozoic** [comment]
I'll reopen this if it doesn't work after it's merged.
:large_orange_diamond:
