### ISSUE TITLE
Possible report spam fix

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#187]
Perhaps the report button should not be visible until players reach level 2?
:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
It's an idea I suggested in the past, but after reflection, if a player has a problem at the beginning of his journey, he will stay stuck...

**Comment by Lymkwi** [comment]
Isn't there a cooldown for reporting already?

**Comment by BetterToAutomateTheWorld** [comment]
@LeMagnesium 
Yes, normally it's a 5 minutes cooldown.

The amount of false/bad report is a problem we probably can't solve...

**Comment by Lymkwi** [comment]
We can't solve false reports with code, only with people.
Should we close this?

**Comment by BetterToAutomateTheWorld** [comment]
Agree, I close the issue.

**Comment by aerozoic** [comment]
What if we made the minimum report length 25 characters? Anything shorter would trigger a simple popup that says something like your report is too short and you need to provide more details.
:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
That's a good idea @cessna151

**Comment by Lymkwi** [comment]
https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/710175d3e4621b955bae6869b44b2aeb24cfcd88

**Comment by BetterToAutomateTheWorld** [comment]
Thank you @LeMagnesium
