### ISSUE TITLE
Unable to break signs

### ISSUE THREAD

**Issue by ElementW** [MinetestForFun/server-minetestforfun-skyblock#19]
Probably from 696135ea9a042e3fde031e17f6b38d5ba13ff226 onwards. Signs cannot be broken, i.e. come back after breaking them.

**Comment by Lymkwi** [comment]
Already fixed. https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/cc396844a91aa2bbb26d4e47071249cfcd071404
EDIT: And https://github.com/cornernote/minetest-skyblock/pull/55
