### ISSUE TITLE
Problem with too similar nicknames

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-skyblock#193]
> From MrBacon/Vault :
> I'm not sure if u had a message or not from vault about one of my accounts but I can't seem to access it as it's saying it too similar to someone else's but it's called APileOfRocks, atm since that I have been on APileOfRocks_ and it hasn't shown that message yet

It's not the first time I saw this kind of issues.

One day, a player can't login because an another player create an account with a name too near his name and one of the two players or both players can't connect again.

**Comment by ghost** [comment]
Fixed https://github.com/MinetestForFun/name_restrictions/commit/19167a0ff194ae6c256b2bd1de09300b976faeba

**Comment by BetterToAutomateTheWorld** [comment]
Thank you @crabman77  for your work
I will merge all servers surely tomorrow, mainly for this fix

**Comment by aerozoic** [comment]
Has this been merged yet? Another player just reported the same problem.
:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
The server are merged since yesterday
