### ISSUE TITLE
IRC bot disconnected on ALL servers!

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#194]
@Darcidride  According to unofficial sources digitalaudioconcepts.com is no longer valid and should be changed to daconcepts.com. I don't know for sure if this will fix the issue.

:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
See here : https://github.com/MinetestForFun/server-minetestforfun/issues/461
