### ISSUE TITLE
You can craft cobble from dirt????

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#195]
Why is there a recipe to craft cobble from dirt? To make cobble you are supposed to cook dirt in a furnace (which still works). The recipe is two dirt next to each other to craft cobble. This recipe allows a player to create massive amounts of cobble in just a few seconds. 

:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
@crabman77 @LeMagnesium 
Didn't we tweak this for a bugfix purpose about quests ?

**Comment by aerozoic** [comment]
Just to add to my previous comment, with just 2 dirt blocks i can have a stack of 60,000 cobble in less than one minute.
:large_orange_diamond:

**Comment by ghost** [comment]
fixed, It was a test code added here  https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/bbea065717a34605378eeab494dd7f0d1e02d61c
