### ISSUE TITLE
Digging clay gives 8 lumps.

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#196]
Should be only 4.

:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
Hi,

If it's 4 in vanilla SB, i think you can tweak it to be 4 again without problem :)

Thank you in advance

**Comment by aerozoic** [comment]
Hmm, that needs to be done on this repo, LOL.
:large_orange_diamond:

**Comment by aerozoic** [comment]
There it is :sunglasses: 
:large_orange_diamond:
