### ISSUE TITLE
Worldmap POI request

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#198]
13211,x, 11301
Name: Ikoma Japanese Gardens
by: tjnenrtn
:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
Added https://github.com/MinetestForFun/xorhub-serverscontents/commit/4782528052c9a6e41eb7d7b8880148f2d9e89038

Will take effect for the next merge
