### ISSUE TITLE
"Place 20 Wood Fences" quest can't be completed

### ISSUE THREAD

**Issue by ElementW** [MinetestForFun/server-minetestforfun-skyblock#20]
Somehow the quest system doesn't count `default:fence_wood` placement, making players unable to complete the "Place 20 Wood Fences" quest and to get to level 3.

**Comment by Lymkwi** [comment]
It happens with every quest. Counters tend to be reset/reactivated. I'll investigate.

**Comment by Lymkwi** [comment]
https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/a9a7dad078b7f9c992876a7cdbd50c91a684315b
