### ISSUE TITLE
Hacker Alert!

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#200]
@Darcidride 
A player dug many cloud blocks from the bottom near 17759,-8,11384. It was reported that this happened about 11:00am Dec. 25 server time. It was also reported that this player gave the cloud blocks to several other players.
:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
Reverted + life banned :
![](http://i.imgur.com/Fd2RLCH.png)
