### ISSUE TITLE
Can't place signs on chests

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#201]
All signs except steel signs can not be placed on the front of chests anymore with shift+click. 
:large_orange_diamond:

**Comment by aerozoic** [comment]
fixed d5b0d32250a8b11331cd01993535e18ee31f3a52

**Comment by BetterToAutomateTheWorld** [comment]
Normally, you can basically place signs on chests with sneak+right click, but maybe i'm wrong
Well, with this fix it's easier for players to do it :)

**Comment by ElementW** [comment]
@Darcidride You still can **not** place signs on chests without Shift+Click, this fixes Shift+Click not working only.
