### ISSUE TITLE
Time can be frozen by ANY player.

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#202]
If any player runs an empty time command "/time" 3 or 4 times within a couple seconds, it will freeze the day/night cycle until the nightly server reboot.
:large_orange_diamond:

**Comment by Lymkwi** [comment]
~~I confirm this. It's weird. I don't understand how /time could affect the time and stop it.~~
Source identified. It's TimeRegulation. When you input /time it doesn't check for a parameter and always assumes you changed the time, and computes a new time speed, a lower one. So it goes from 11 to 0.001 pretty fast.

**Comment by BetterToAutomateTheWorld** [comment]
Thank you for the fix @LeMagnesium
