### ISSUE TITLE
Prevent sambot abuse on IRC.

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#204]
@LeMagnesium Many users have discovered the Sambot command "anonymous say". It is only a matter of time before it gets abused. Can you disable this command?
:large_orange_diamond:

**Comment by Lymkwi** [comment]
![sambot_fix_anonymous_cap](https://cloud.githubusercontent.com/assets/6785985/22660563/552a08e2-eca2-11e6-82b4-26335ff0c2ac.png)
Fixed.
