### ISSUE TITLE
Worldmap POI requests

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#208]
I have a few new ones...

1.  SKYWAY Central Station (13375,x,11200) by tjnenrtn
2.  Airport (18860,x,13450) by beldin
3.  The Cross (13400,x,14130) by TheWild

:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
Done
1. ![](http://i.imgur.com/m2w4Plq.png)
2. ![](http://i.imgur.com/k8evcor.png)
3. ![](http://i.imgur.com/ILCcr9F.png)
