### ISSUE TITLE
Worldmap not rendering correctly

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#209]
http://158.69.114.146:8811/#9/16440.0000/15758.5000

Many nodes are now invisible. 

###### _thanks to beldin for the report_ ######
:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
We updated yesterday mtsatellite, it's the cause of the issue.

That's a bit curious, I checked the _colors.txt_ file and it's ok (generation and content), I need to check the **mtsatellite** project to check if the parsing of this file has changed since the last version...
_(PS : apparently no)_

**Comment by BetterToAutomateTheWorld** [comment]
Well I've maybe the solution, I will relaunch the **mtseeder** to see if the sync with _colors.txt_ generated by the _automappercolor_ script

Maybe @s-l-teichmann have an advice or an idea before i did that ?

**Comment by aerozoic** [comment]
It works now
:large_orange_diamond:
