### ISSUE TITLE
Add MFF tools textures

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-skyblock#21]
Actually all of the weapons have the same texture (size/details) and there are in 16px. :/ 
Only the color change, that's the default minetest_game textures, so... that's not very beautiful... (understand : ugly)

We need to add the MFF tools textures to the subgame.

**Comment by BetterToAutomateTheWorld** [comment]
I think it's done with this commit, can you confirm @LeMagnesium ? https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/86ce405f9a003dd54492150025c92fa44b0693de

I closed the issue.

**Comment by BetterToAutomateTheWorld** [comment]
Reopened the issue, need to removed the swords textures, there are useless, we removed the swords on the Skyblock server

**Comment by Lymkwi** [comment]
https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/85908dbd33aedcd37da78501e1d5a234942c1e68

**Comment by BetterToAutomateTheWorld** [comment]
Thank you
