### ISSUE TITLE
All servers DOWN!!!

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#212]
@Darcidride All servers have been down for several hours!
:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
Ok, the server is rebooting, it will be up again in some minutes

it's really weird because it's a kind of half kernel panic which touch the network part of the VM, i need to investigate, it's maybe a bigger problem (KVM ?) or something, don't know for now...

**Comment by BetterToAutomateTheWorld** [comment]
Ok weekly backup issue (hypervisor side), fixed since i revert my recent changes on this node backup

(_PS : for information, the servers was offline since the 19th april 7:30AM_)(17 hours)
