### ISSUE TITLE
hud textures

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-skyblock#22]
We need to add the hud textures of the MFF & MFF-HG server, the actual texture is ugly with a 16slots hudbar.

**Comment by BetterToAutomateTheWorld** [comment]
Assigned this issue to @fabienwang because in this way he can learn how the hud works :) (and it's a simple an fast issue)

**Comment by Lymkwi** [comment]
The important textures are `crosshair.png`, `hudbars_bar_background.png`, `hudbars_hotbar.png`, `hudbars_hotbar_selected.png` from [hudbars mod](https://github.com/MinetestForFun/server-minetestforfun/tree/master/mods/hudbars/textures). I will also have to copy some code from hudbars into default/init.lua to use these textures, so please, put them in default's textures folder, and replace 'hudbars' with 'default'.

**Comment by Lymkwi** [comment]
https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/3f3de7073f1045242afe2c7024c1b0dd02c972b7
