### ISSUE TITLE
Problems connecting to the server

### ISSUE THREAD

**Issue by arielenter** [MinetestForFun/server-minetestforfun-skyblock#226]
There seems to be a problem with xorhub MinetestForFun **SKYBLOCK**. When I try to connect I get the following message: "this server has experienced an internal error" and I don't see any player is connected right now.

I saw that there was a scheduled maintenance but apparently it should be already over.

I hope this is temporal. Thank you.

**Comment by BetterToAutomateTheWorld** [comment]
Hi,

Thank you for your report, i'm on it, the server will be online again in some minutes.

**Comment by BetterToAutomateTheWorld** [comment]
It's now fixed, thank you again for your report! :)
