### ISSUE TITLE
IRC server down forever

### ISSUE THREAD

**Issue by YuGiOhJCJ** [MinetestForFun/server-minetestforfun-skyblock#233]
Hello,
After a discussion on IRC (freenode, #minetest) with VanessaE today, I discovered that the IRC server used by MFF (irc.inchra.chat) is down forever:
```
<YuGiOhJCJ> VanessaE, hello since several days I am unable to join the famous inchranet IRC network, is there a maintenance please?
<VanessaE> inchra is basically dead.
<VanessaE> I shut my irc server down
<VanessaE> go to #ve-minetest-servers here on freenode.
<VanessaE> that's the official channel now.
```
So maybe we should use freenode now?
Best regards.

**Comment by arielenter** [comment]
I went to #ve-minetest-servers at freenode, but it seems only developers or authorize users can send messages there? I wanted to ask if someone knew what is the status on the skyblock server.

When I tried to send a message in the IRC channel I get the following message back:

"Cannot send to channel"

**Comment by YuGiOhJCJ** [comment]
The #ve-minetest-servers channel is for the VanessaE's Minetest servers. If you want the channel for the MFF Skyblock server, go to #xorhub-minetest-skyblock (https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/47970ecc9902d8ffaa599fe9910159f52edcec51). However, I have no idea about the status of the MFF Skyblock server.

**Comment by BetterToAutomateTheWorld** [comment]
All of our IRC channels are now on freenode :
- #xorhub-dev
- #xorhub-minetest-classic
- #xorhub-minetest-creative
- #xorhub-minetest-hg
- #xorhub-minetest-skyblock
- #xorhub-teeworlds
- #xorhub-warsow

The MFF bots are now on this channels

_(PS : only Classic and HG servers are running currently, the SB and creative will be online again soon)_
