### ISSUE TITLE
Level 3 place 4 steelblocks

### ISSUE THREAD

**Issue by ghost** [MinetestForFun/server-minetestforfun-skyblock#24]
I'm at level 3, place 4 steelblocks
Problem is no previous quest rewards us with steel ingot or i'm dumb ?!

**Comment by ghost** [comment]
Désolé, j'ai trouvé après avoir recommancé les quètes. peut-être dans les astuces on peut mettre "n'hésitez pas à vous faire un livre et y écrire vos recettes à ne pas oublier..."

**Comment by BetterToAutomateTheWorld** [comment]
Tu obtiens des copper ore level 2, c'est le premier minerai que tu obtiens enfaite. 

Suite à cela tu craft un scau avec des steel ingot (cooper ore fondu = steel ingot)

Donc pour faire le steel block, tu as besoin de copper ore, les fondres, en faire des steel ingot, et mettre 9 steel ingot dans la craft grid ;)

**Comment by farfadet46** [comment]
après j'ai remarqué qu'on pouvais n'en faire qu'un seul, le poser/casser 4 fois en fait c'est volontaire de compter "que la pose" ?
PS: c'est valable pour toutes les quettes en fait non ?

**Comment by BetterToAutomateTheWorld** [comment]
@farfadet46 Oui c'est normal, et c'est mieux ainsi pour t'éviter de te tuer en boucle pour récupérer de la Dirt car tu n'en a pas assez par exemple
