### ISSUE TITLE
Water Usebug

### ISSUE THREAD

**Issue by Ataron** [MinetestForFun/server-minetestforfun-skyblock#25]
Actually we can put/take water source in other's areas. I don't think it's a good thing.

**Comment by BetterToAutomateTheWorld** [comment]
- [x] First, reduce the propagation of the water to 3 blocks => https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/cf9879d6f74364403b54550a1bf0d2269b93ac09
- [x] Second, slow down the water flowing refresh to 1 block each 5seconds => Ten is REALLY slow (5 is better) https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/2672a188c4bce3c5d9118cb23f35f2b10d2bc1b7
- [x] Forbidden the water put feature on ALREADY PROTECTED AREAS => https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/9f87fb7d382441eaca7184ad7b625459ccb1520b
- [x] Finally, apply also this fix to the MFF CREATIVE  => Same, 5 is good, ten is too slow https://github.com/MinetestForFun/server-minetestforfun-creative/commit/3c72c1b3cacaff63f5c780cf3169ef6e2863294b and https://github.com/MinetestForFun/server-minetestforfun-creative/commit/f628b958dc8341622e9487c63e18cb4aae895bf0

Mg worked on this priority.
