### ISSUE TITLE
Bug with the papyrus growth

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-skyblock#26]
Reported by @KasBrick :

```
D'ailleur EnB, a parlé d'un probleme, je crois qu'il m'a dit qu'après avoir fait pousser des papyrus son block de protection a disparu.
```

Translation:

```
By the way EnB told me about an issue, IIRC he said that after growing papyrus his protection block disappeared.
```

This error is like the tree/schematic problem we found on MFF earlier.

Need to check first, and fix if it's possible.

**Comment by Lymkwi** [comment]
Do a rollback_check on the position and tell me what was the last interaction on the block please.

**Comment by KasBrick** [comment]
I can't help you more :/ EnB no tell me more about this.

**Comment by BetterToAutomateTheWorld** [comment]
I don't know where is the EnB's house, it's complicated to find him with this hundreds of islands...
I think you can forget the rollback_check :p

**Comment by Lymkwi** [comment]
Papyrus don't seem to destroy protector nodes. I have no idea how they disappeared.

**Comment by KasBrick** [comment]
I found the island (16064.8, 5.0, 15586.9).

**Comment by BetterToAutomateTheWorld** [comment]
Thank you @KasBrick 

With this position, I will check this night the "rollback_check"

**Comment by Lymkwi** [comment]
Papyrus do not destroy protection block, I'm positive about that. Find the reason for which the node disappeared and close this issue.

**Comment by BetterToAutomateTheWorld** [comment]
Surely not a bug but the lag, closed the issue.
