### ISSUE TITLE
Warp crystal 

### ISSUE THREAD

**Issue by farfadet46** [MinetestForFun/server-minetestforfun-skyblock#27]
the warp Crystal protect all the area and we can't expand our area :(
like at the cyberpangolin's factory

**Comment by BetterToAutomateTheWorld** [comment]
Peux tu reformuler en français s'il te plaît ? Je ne comprend pas bien :/

**Comment by ObaniGemini** [comment]
I'm moving this issue to mff repository

**Comment by ObaniGemini** [comment]
I'm moving this issue to mff repository

--> https://github.com/MinetestForFun/server-minetestforfun/issues/284

**Comment by BetterToAutomateTheWorld** [comment]
Merci @ObaniGemini
