### ISSUE TITLE
Ajout de droit

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-skyblock#30]
Ajouter une petite ligne pour donner ces droits a la connexion d'un joueur : home, spawn, fly, fast, shout

Obligatoire car j'avias oublié de mettre ces droits par defaut dans le minetest.conf...

**Comment by Lymkwi** [comment]
https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/ab94c4dea95e1778472312e8f1197020963e5ed9
Tu l'as déjà fait, non?

**Comment by BetterToAutomateTheWorld** [comment]
Le _minetest.conf_ ne modifie les privilèges qu'à la première connexion.

Il nous faut ajouter un bout de code qui rajoute ces privilèges à la connexion du joueurs car tous les joueurs étant déjà connectés n'ont pas certains droits.

**Comment by Lymkwi** [comment]
J'aurais pu aller lire le nom des fichiers dans `minetest.get_worldpath() .. "/players/"`et redonner à tous les privilèges mais j'ai préféré cette méthode : https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/7bd7cacc9042033b94d424ba09b68f571849ef51

**Comment by BetterToAutomateTheWorld** [comment]
Je préfère cettte méthode aussi.

Merci :)
