### ISSUE TITLE
Hide hearth after level 4 completed

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-skyblock#33]
After a player completed the level 4, it will be a great idea to hide his hearth bar because he doesn't need it anymore.

The "normal players" (levle 0 to 3) need they hearth bar because they can die. (by falling for example)

**Comment by Lymkwi** [comment]
I don't think it's a good idea. You can still die in level 3, and that would be misleading to hide the bar and let the player think they are invisible.
~~EDIT: And recently dues to an update I think the health bar has disappeared.~~ It was just `mff_hud`. Fixed. https://github.com/MinetestForFun/mff_hud/commit/cb64a13e163f26ad6d4d027bf3338e8ac351b41c

**Comment by BetterToAutomateTheWorld** [comment]
you can't after you complete the level 4, when you have fly+fast, if you fall down (cloud for example), you're teleported to your home point.

**Comment by Lymkwi** [comment]
We chose not to change anything. Shall I close this?
