### ISSUE TITLE
random_messages

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-skyblock#35]
Need to add some difficult/hard to find recipes in [random_messages] mod

From this page https://cornernote.github.io/minetest-skyblock/items/

**Comment by Lymkwi** [comment]
https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/12db8db6ece6efb4c0454e1ab644165bd645fd5f
See #36 though, it might be easier to do.

**Comment by BetterToAutomateTheWorld** [comment]
Add a random message for this recipe :
http://cornernote.github.io/minetest-skyblock/items/default-sand/

**Comment by Lymkwi** [comment]
https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/d5b96b8ded26ee8b00e74d81ff083add3925f0b6
