### ISSUE TITLE
Add an external craft guide

### ISSUE THREAD

**Issue by Lymkwi** [MinetestForFun/server-minetestforfun-skyblock#36]
I think we should add a craft guide mod, like `craft_guide` modpack, instead of having to guess recipes.

**Comment by BetterToAutomateTheWorld** [comment]
Only when the player completed all quests/levels => yes

Actual inventory => no more quests/levels => unified inventory ?

**Comment by Lymkwi** [comment]
I could give it as a reward for the last level, and disable its craft. That's the easiest way of doing so.

**Comment by Lymkwi** [comment]
Activating unified_inventory only after a player finished the levels is horriibly complicated to code; just adding an uncraftable craft guide for players when they finish level 3 is enough. Or, I can also add the mod, and prevent players from crafting a craft guide if they have not finished level 3 (just a few lines in a on_craft).

**Comment by BetterToAutomateTheWorld** [comment]
A node wich show the craft guide is a good idea, only available after the levels completion

**Comment by Lymkwi** [comment]
That's what you already told me, what I wanted to tell you was how I would do it. The only ways of regulating the possession of such guides are :
- Preventing craft if not level 4 (heavy, needs more code)
- Give one as an award for the end of third level (only needs to remove the craft recipe, but players who already reached level 4 won't get any)

Pick one.

**Comment by BetterToAutomateTheWorld** [comment]
Definitely the second

**Comment by Lymkwi** [comment]
Wait. You're picking the one that lets all old players not have a craft guide whereas new players would get the craft guide? I seriously thought you would take the first one.
Anyway I can't find any good craft_guide mod out of u_inv so I need to find one first.
Also, why wouldn't players at levels 1, 2 or 3 have the right to use a craft guide?

**Comment by BetterToAutomateTheWorld** [comment]
In my point of view, forbidden the craft guide for new players isn't a good idea, if players don't want to compelte all levels before build somehting, there are blocked...

I think the "craft grid help" should be a node, like a bookshelf or workbench, maybe with new texturing.

If you really want to forbidden this node from players which not completed the level 4, we can with a check/condition forbidden the right click on this node, i presume. Or we can simply make this node like locked chest, only used for the players whith put it. Like you want to code ;)

For the mod, this mod https://forum.minetest.net/viewtopic.php?f=11&t=2334&hilit=grid seems like we need. (from cornernote :p)

**Comment by Lymkwi** [comment]
I was thinking from the beginning that you wanted the craft guide to be only usable/craftable by players above level 4. Thank gods, I was wrong. I'm in favour of allowing it for everybody.
And also I don't like `craft_guide` because you have to modify every mod's depends.txt to load it before. But I will try to make it work even without that.

**Comment by ObaniGemini** [comment]
Maybe to craft it, use mese, bookshelf and ?¿

**Comment by Lymkwi** [comment]
The original craft looks like that : 
![Craft Guide](https://lut.im/5In8ZpFUIE/IzOvMkDpWGTd5Iga.png)

I think we should stick with that (no pun intended). Also I think we should remove the craft computer, it's not useful when you already have the sign.

**Comment by Lymkwi** [comment]
I added `[craft_guide]`, working without having to modify anything else. If you still want to add modifications tell me.

**Comment by BetterToAutomateTheWorld** [comment]
Yes, removed the computer is a great idea.

For the craft recipe of the craft guide i think something like this will be more interesting :

```
First idea :
S         S             S
S         S(or B)       S
F         F             F
S = Sticks
F = Wooden Fences
(B = Book)

Second idea :
S         S             S
S         B             S
X         F             X
X = Empty slot
```

So in this way, from the middle of the level 1 players can craft the **[craft guide]** item.

**Comment by ObaniGemini** [comment]
I prefer the second idea

**Comment by Lymkwi** [comment]
Yes, me too. I'm going to remove the computers and put the new recipes for the unlocked craft_guides. (locked guides are crafted with one craft_guide put over a steel ingot)

**Comment by Lymkwi** [comment]
![](https://lut.im/1jx7DB8xlJ/ERfiVriFz37pD7o1)
![](https://lut.im/mgkv7lytTE/pXHSnPvtoFPFspO9)

**Comment by Ombridride** [comment]
Great, just need to add the recipes compatibility now :)

**Comment by BetterToAutomateTheWorld** [comment]
Finally, good job ! :)
