### ISSUE TITLE
Little tweak about crafts

### ISSUE THREAD

**Issue by ObaniGemini** [MinetestForFun/server-minetestforfun-skyblock#38]
I want to point a little problem I encounter with some little crafts.
Let's take an example, to craft an iron mineral, you need an iron lump and a stone block.
You will place it like this : ( I = iron lump ; S = stone block )
I
S

The problem is that you can only place it like that, and not in the four ways the grid allows to place them.
The idea would be to able those little crafts to be craftable in all kind of directions.
This would enable : All minerals, coloured wools, mossy cobble, paper, books.

Please help in filling this list if this feature interests you.

**Comment by Lymkwi** [comment]
I don't think there is any colliding craft recipe with those methods, at least in skyblock so far. The only problem I have is that it will create 4 times more occurences of `minetest.register_craft`, and as we all know, the less we call the engine, the faster it works.
So far I don't see any advantage that could balance with having to write 4 times more crafting code, so I would rather disagree with that idea. But we need other devs' opinions.

**Comment by BetterToAutomateTheWorld** [comment]
I also disagree, in my point of view it's not necessary, craft guide is here and the "help tip" feature for quests are great.
If players don't remember how to craft items after this features... We can't do anything more...

**Comment by BetterToAutomateTheWorld** [comment]
I closed the issue, we disagreed with this feature because it's too heavy and not so useful.
