### ISSUE TITLE
Add the [player_inactive] mod

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-skyblock#39]
from the HG server, with the same values

**Comment by ObaniGemini** [comment]
Well skyblock is mostly a creative server, maye shall we have the harcore/creative server values ?
Other players shall not be blocked by inactive player, as in a HG or a CTF

**Comment by BetterToAutomateTheWorld** [comment]
That's correct, let's try a 60 minutes value ;)

The problem is now to get free slots when we reach a too big number of inactive players which consume (mainly) bandwich and memory :)

**Comment by ObaniGemini** [comment]
Well 30/20 minutes seems to be nice to me, but not 5/2 minutes as in HG :p

**Comment by BetterToAutomateTheWorld** [comment]
HG is now 15min ;)
