### ISSUE TITLE
finished quests need sounds

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-skyblock#4]
Need to add a sound when you finish a quests, and an another sound when you finish a level !

**Comment by ObaniGemini** [comment]
- [x] finish quest (player)
- [x] finish level (player)
- [x] finish level (other players)

**Comment by Ombridride** [comment]
Up, need to do it as soon as possible because we need to finish our skyblock "subgame_base" ;)

**Comment by Ombridride** [comment]
Up

**Comment by farfadet46** [comment]
there is 2 sound maybe you can use it (made by me)

ding : https://up1.ca/#aj7IbK1lcNfYeJxSYwsmDw
and
dong : https://up1.ca/#PWFs3VifGpGeSOOGPBXI4g

PS: au début il s'agissait d'un seul ding dong.

**Comment by ObaniGemini** [comment]
Can someone add commented lines with skyblock_finish_quest.ogg, skyblock_finish_level_player.ogg and skyblock_finish_other.ogg ?
It will allow me to close the issue when I'll push the sounds

**Comment by Lymkwi** [comment]
We only need to sounds to uncomment those lines : https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/4bb0869ada32fb8b94a039a97d913da2074673d9

**Comment by BetterToAutomateTheWorld** [comment]
up

**Comment by ObaniGemini** [comment]
I won't be there for some time because of personnal reasons. Please excuse me.

**Comment by BetterToAutomateTheWorld** [comment]
I find this on OGA : 
- http://opengameart.org/content/level-up-power-up-coin-get-13-sounds
- http://opengameart.org/content/completion-sound

The two set of sounds can be a little tweaked a used for the finish **quest (player), finish level (player), finish level (other players)** :)

**Comment by ObaniGemini** [comment]
There's also the award sound that is available. I think that there is one of the 13 sounds set that would be good.

**Comment by BetterToAutomateTheWorld** [comment]
Please, can you isolate the sounds and send them to us ? Then, we will introduce them in the server
