### ISSUE TITLE
Replace [craft_guide] with [command_craft_guide]

### ISSUE THREAD

**Issue by Lymkwi** [MinetestForFun/server-minetestforfun-skyblock#42]
Our version of the [craft_guide] mod triggers obscure crashs and has apparently many bugs. I've written a craft gude mod relying on chatcommands.
[There](https://github.com/LeMagnesium/command_craft_guide) it is.

It's supposed to solve : 
- #41 
- #40
- many other crashes that were not reported

Things that I'll do :
- [X] Inhibate craft_guide (https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/5e04d4a5159da3b2daae402b1a651525aaa5131f)
- [X] Put an ABM in charge of replacing the signs (https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/06978d0ef7243c2c80f8ee99e79591bfa5ffbf97)
- [X] Erease the code from our repository (After next merge : 1 week left)

**Comment by BetterToAutomateTheWorld** [comment]
I think the 1 weak countdown is over, can you "Erase the code from our repository" and closed this issue please ?
