### ISSUE TITLE
sethome / gohome button

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-skyblock#44]
Some players ask me for add a **sethome**(/sethome) and **gohome**(/home) buttons like unified_inventory do it n they inventory

**Comment by Lymkwi** [comment]
Do they realize how horrible it is to have to change some of skyblock's deep code to fit their wills?
Anyway, it's done, and surprisingly quite clean.

**Comment by BetterToAutomateTheWorld** [comment]
Perfect, you're the best ;)
