### ISSUE TITLE
Spawn/sethome/home and inventory

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-skyblock#45]
#### Spawn Point
- [x] add the spawn mod => https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/c465fe743f6d6da1fb7f1ce8bc04f009368496a4
- [x] set a spawn position in the minetest.conf
- [x] add a button on the player inventory to use it easily => ~~https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/c465fe743f6d6da1fb7f1ce8bc04f009368496a4~~ => Need to re-add this feature because of the new inventory ! => https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/02459eccd566067f869d0b04f8fbb33c0690d003
#### Set Home & Home

Also, i'm thinking about this :
- [x] ~~Add a "sethome" & "home" button to the player inventory~~ (Already done, my bad)

**Comment by Lymkwi** [comment]
(We're gonna run out of place to add buttons at this rate...)
Do we put an action timer over the use of the spawn command and button?
Also, considering that the spawn position will be visited by a lot of players with more or less good motivations to be there, I think you should build a spawn house, or something like that, in an unbreakable material, and use its position as a spawnpoint.

**Comment by BetterToAutomateTheWorld** [comment]
Yes, the place will be a problem at this rate :)

No need to add a timer for the **spawn** command

Yes, i'm open to suggestions for a spawn point, i don't know where exactly to put it... Let's give your ideas :)

We can eventually build a spawn house/building, in unbreakable way, i agree

**Comment by Lymkwi** [comment]
> Yes, i'm open to suggestions for a spawn point

At about the center of the map should be good, but why not around (16336, 15704)? That would connect it to the city in building.

**Comment by BetterToAutomateTheWorld** [comment]
Good idea, i cleared this area for cessna151 a few days ago but i can used it for a little spawn building, or maybe cessna151(or other players) can build it, i will ask him(them)

**Comment by aerozoic** [comment]
/spawn works now :-) 

Don't forget the spawn button in inventory.

**Comment by BetterToAutomateTheWorld** [comment]
Spawn point inventory button texture for @gravgun 

![spawnpoint_button](https://cloud.githubusercontent.com/assets/8619233/12129143/027dbce4-b402-11e5-9680-26a8bb3e7865.png)

**Comment by aerozoic** [comment]
Spawn building structure is done. It just needs interior decoration. How do you want to post rules? 

I'm planning to add a "Noob corner" somewhere in the spawn house that will explain and give examples of things that aren't obvious to noobs. (for example: how a protected chest is different from a locked chest)

**Comment by ObaniGemini** [comment]
@cessna151 : prefer "newbie" to "noob" ;)
Also I think rules will be displayed as in all our other servers : on locked signs (10-12)

**Comment by aerozoic** [comment]
Yeah i will name it something more professional in the game.

**Comment by Lymkwi** [comment]
[There](https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/02459eccd566067f869d0b04f8fbb33c0690d003) is the button.

**Comment by aerozoic** [comment]
Mg, when testing locally, the button doesn't have a popup text when hovering the mouse. I forgot what that's called. Tooltip maybe?

**Comment by ghost** [comment]
@cessna151 Tooltip fixed https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/afe29c0d26874a3df09d4fddd15e1efee3fe2991
