### ISSUE TITLE
Numeric input in craft grid.

### ISSUE THREAD

**Issue by rredesigns** [MinetestForFun/server-minetestforfun-skyblock#48]
Usually, using a PC to craft in the game, can ruin a mouse pretty fast after so much clicking. A normal crafting is never a task to make just one stick/ore/etc, so, in order to make it easier, faster and at the same time less harmful to mouses (no idea how it works in mobile), I suggest either a numeric input or an accumulative click routine, so just one click is needed to craft as much as needed. 

Also, two small buttons above the grid with amounts like [50] and [Max](last one uses up all materials in available in the grid), would be much appreciated.

**Comment by rredesigns** [comment]
I recently found that using the middle mouse button can make crafting easier. The Max button would still be a great feature though.

**Comment by Lymkwi** [comment]
The problem though is that we can't really control such feature in Lua, only the engine developpers would be able to implement this properly. As far as I know it's doable in a mod, but it would be a disgusting hack to implement when it should clearly be done by builtin or the engine.
(I'm just gonna try to see how bad it looks like)

**Comment by ElementW** [comment]
Much more of a hack / workaround than a real solution.
However given the coredevs' stubbornness, I doubt if we ever made a PR to the engine they'd accept it briefly (they always find a way to piss you off either about code style, efficiency (which is inexistent in their engine) or implementation details).
Just look at how much time it took them to implement shift-click stack movement ([c977fbd](https://github.com/minetest/minetest/commit/c977fbd9288d0e80019554411a2f1885f7760568)) or even implement the middle click _which itself is a dirty workaround to craft more stacks at a time_; these features were requested for years, and in comparison Minecraft implemented it early in its development (along the lines of the first Alpha versions).

But sure, that could be done and given the coredevs'... _relative speed_, that's the only plausible workaround I see.

**Comment by Lymkwi** [comment]
https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/9998b5808e13638ad7a5a6eb845288fe719306af
This implements a max button.
Considering how obnoxious that was to code, and also how much space is left on the players' inventory, I highly doubt a numeric input field would be worth the efforts of implementing it.

**Comment by BetterToAutomateTheWorld** [comment]
Middle mouse click (10) + max button seems to me good and make easier the way to craft easier big amount of items.

I closed the issue
