### ISSUE TITLE
Easier lumbering.

### ISSUE THREAD

**Issue by rredesigns** [MinetestForFun/server-minetestforfun-skyblock#49]
I've seen this mod used in other skyblock server so I know it works and works well. Don't know if is a public mod in Minetest forums or a server custom, but is pretty neat and all players will love it.

When cutting the base of a tree, all the wood chunks and saplings go down and are added to the inventory, as they would if you had harvested all of it manually.

Maybe saplings is not needed, but in real life trees fall when you cut them, so I think it will be a natural feature for us to have.

**Comment by Lymkwi** [comment]
There are actually multiple mods which do that, among which `treecapitor` (I think that's its name).
We could also code that into default. That's done in a few lines for the default tree, but it's harder for ~~pines~~ acacia trees and jungletrees.

**Comment by ElementW** [comment]
@LeMagnesium That's `treecapacitor` you meant there.

**Comment by Lymkwi** [comment]
@gravgun : Exactly. However, I couldn't find it in my mod database, so I'm going to code that on `default/functions.lua`, but only for normal trees and pines.

**Comment by rredesigns** [comment]
Oh, great!!!!!!!!!!. 

Magnesium, you are my new hero. :D

**Comment by BetterToAutomateTheWorld** [comment]
We can't do this only for normal trees and pines. We need to do this also for jungletree, it's a must have feature for consistency ;)

**Comment by Lymkwi** [comment]
> feature for consistency ;)

Look at how consistent the patterns for scattering trunk nodes are for acacia and jungletrees :

![](https://lut.im/5nFwkbT6tY/zwpYCUjQiTiYEquO)

![](https://lut.im/QRLaYUk7W1/58QWAPMTZdUvk9dD.png)

I could try something for the jungle trees though, considering it's probably a bit better than I expected (since the tree definition changed in 0.4.10 I think), but I can't help with the base of the tree, nor can I do something for the acacia. (By the way do we even have acacias in skyblock?).

**Comment by ElementW** [comment]
@LeMagnesium Acacia nodes and saplings do exist in SB but can't be obtained (except using `/give`).

**Comment by rredesigns** [comment]
Same problem this mod had in the other server, though is nothing compared to chopping every single block (in pines is a very long task).

 In Skyblock however we only have apples and pines as the most common types.

**Comment by BetterToAutomateTheWorld** [comment]
This issue is over, no need to use treecapitator for acacia for now because it's not implemented yet in the Skyblock Subgame :)

I will merge soon the server to add this feature.
