### ISSUE TITLE
Website update

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-skyblock#5]
- [x] Add a banner for announce the SkyBlock server openning !
- Maybe do an article about the SkyBlock game !

**Comment by BetterToAutomateTheWorld** [comment]
Someone can do a Banner please ? my skills for this kind of things aren't very good :/

@Ataron @Cyberpangolin @ObaniGemini

**Comment by Ataron** [comment]
What do you think about that : https://lut.im/2rDGc4B25e/2PJbpK5J.png ?

**Comment by ObaniGemini** [comment]
@Ataron : this is too confused. The letters are too much exposed. But the fonts aren't so bad.
Also I think you should take a screenshot from the server, with many buildings :)

**Comment by BetterToAutomateTheWorld** [comment]
Really Great beginning ! 

Need a try without the left and right ''skyblock'' border,  also need a try with a different background,  like the actual server buildings 

You can add some custom borders if you want. 

The policy and text are perfect.

**Comment by Ataron** [comment]
I had a size problem cause the last banner you wanted was in 1452*452, but my screen resolution was too small and the screenshot didn't do all the picture. I will try to do another one with others scrennshot.

**Comment by BetterToAutomateTheWorld** [comment]
We need a 1450*450 resolution. 

The last one you send to me,  I had to resize it.

**Comment by Ataron** [comment]
I'll try to finish it tomorrow and Wednesday if not finished yet.

**Comment by Ataron** [comment]
https://github.com/MinetestForFun/server-minetestforfun/commit/a46264797c01cbd847d77dc415c0789727fbb647

**Comment by ObaniGemini** [comment]
I made this version with corrected things https://imgrush.com/Y2B-rk6jtr3s

**Comment by BetterToAutomateTheWorld** [comment]
Ok, i will add this modified version

**Comment by BetterToAutomateTheWorld** [comment]
Done.

The cache of the website will be reseted automatically and the new banner will appear in some days.
