### ISSUE TITLE
Short tree.

### ISSUE THREAD

**Issue by rredesigns** [MinetestForFun/server-minetestforfun-skyblock#50]
Small, craftable tree. Crafted with pine sapling and Round-Down (to limit it's growth), though it might be to hard to code that way, so also bucket+dirt+sapling could work to get a tree in a pot.

**Comment by ElementW** [comment]
Hum IDK if you can add wear to tools in the crafting grid. So the 2nd crafting recipe seems more feasible.

**Comment by rredesigns** [comment]
I know. Also more intuitive. It should look like a small cipress in a pot. I'll have captures later. BTW, how should it be made?

**Comment by BetterToAutomateTheWorld** [comment]
-1
I don't agree with this idea.
No need to add more tree schematics for the moment, we have other "real" trees to add in the next levels, like the acacia tree

**Comment by rredesigns** [comment]
Well, those trees can't be used as in house decoration, unless you have a mansion, and still, would look bad. 
 I think I should've mentioned it will be like 2-3 cubes high.

**Comment by BetterToAutomateTheWorld** [comment]
If you want a small tree you can put a sapling deeper, if the surface is at "x,0,z", put your sapling in a hole in -2 for example and your tree trunk will be small ;)

**Comment by rredesigns** [comment]
I know, but just look at what I mean, then tell me how much of a bad idea it is. :D 

[Here:](http://i.xomf.com/hlfxl.png)  Sorry about the perspective. I have no idea what focal lenght MT camera uses. :p

**Comment by rredesigns** [comment]
Also, a regular sapling twice as high is good too, after all, is just to decorate. Also, if not the whole tree, cosider at least the pot as a map model to plant several stuff on it.

**Comment by ObaniGemini** [comment]
Skyblock is meant to be light and simple, so I don't think there would be room for that kind of things. But it would fit greatly in our creative server repository ! ( https://github.com/MinetestForFun/server-minetestforfun-creative/

**Comment by rredesigns** [comment]
Is a very simple model, can't get it lighter than that. But I think I understand. You can close this issue then, but consider making the pine sapling taller, please.

Btw, if you want that model, tell me and I'll give you the .blend fiel.

**Comment by BetterToAutomateTheWorld** [comment]
If you want you can give us the .blend file for an eventually addition on the Creative server :) (please open an issue on the creative server, it will be easier for us)

I don't think we should tweak the base/subgame core schematics...

I closed this issue, thank you anyway for your idea
