### ISSUE TITLE
sound when player eat something

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-skyblock#51]
Add a sound when a player is eating something will be great (like hunger does from classic server)

**Comment by ObaniGemini** [comment]
I'll can make one when I'll be back (soon)

**Comment by BetterToAutomateTheWorld** [comment]
We have already this kind of sounds in classic, i think it's enough :)

**Comment by Lymkwi** [comment]
`hbhunger` is responsible on Classic for the sound emitted when someone eats.
It was very easy to copy.

**Comment by BetterToAutomateTheWorld** [comment]
Yes, I was wondering this, thank you for the add.
