### ISSUE TITLE
Protection recipe creates one item instead of 4 (as usual)

### ISSUE THREAD

**Issue by rredesigns** [MinetestForFun/server-minetestforfun-skyblock#52]
The crafting of either logos or boxes produces just one instance in the output per recipe rather than 4 as it was previously.

**Comment by Lymkwi** [comment]
We replaced our version of `protector` by a submodule referencing protector's upstream repository. Thus, the craft was updated.
We should fork protector, and work on our repository.

**Comment by BetterToAutomateTheWorld** [comment]
Yes @LeMagnesium 
And we need to add the new super_protector_block/lock on this forked repository of "protector"

**Comment by rredesigns** [comment]
I will be done.

In the mean time, let's fix what's broken. :D

**Comment by ElementW** [comment]
MinetestForFun/protector@3665f39aa490adb2eec0d7b0e7908328feb0582c
