### ISSUE TITLE
Remove the area privs

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-skyblock#53]
I need to remove the area privs from the file manually, it will take some minutes with a regex and will be applied after a reboot
Anyway, the mod area aren't here anymore so the actual priv for players isn't very important

**Comment by Lymkwi** [comment]
Can't you just shut the server down for a minute and before restarting do this? :

``` bash
sed -i "s/areas\,//" ./auth.txt
sed -i "s/\,areas//" ./auth.txt # Just in case it is the last one
```

**Comment by BetterToAutomateTheWorld** [comment]
That's a regex with sed, that's why i planned to do ;)

**Comment by BetterToAutomateTheWorld** [comment]
Done, it will be applied at the next reboot of the server.
