### ISSUE TITLE
new skyblock texture

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#58]
Somebody mentioned a couple weeks ago something about making a new skyblock texture to replace the "?" but i don't remember who or why it was mentioned. Anyway, i was bored and made this texture:

![skyblock_quest](https://cloud.githubusercontent.com/assets/15715378/12148015/0e3633a0-b46a-11e5-96fe-0bbd50e5162a.png)

Like it, hate it, edit it, or use it if you wish. It's up to you.

**Comment by Lymkwi** [comment]
@gravgun , that's for you.

**Comment by BetterToAutomateTheWorld** [comment]
Beautiful ! But maybe too colorful compared to the other icons :p

EDIT : After reflexion, the "?" seems perfect to me for the "quest" icon (like many MMO/RPG, it's a standard)

**Comment by rredesigns** [comment]
In the case of the quests, probably it would be better to use "!!" instead of "?".  So the player will be dragged to check it, instead of just ignoring it.

**Comment by BetterToAutomateTheWorld** [comment]
or maybe the classic quests icon should be good, anyway, "?" or "!" it's understandable ;)

**Comment by rredesigns** [comment]
Or maybe a girl in bikini. :p

**Comment by ObaniGemini** [comment]
I think he watched the Teen/Adult topic on MT forum...

**Comment by rredesigns** [comment]
I did. XD

**Comment by aerozoic** [comment]
How about this one...

![skyblock_quest1](https://cloud.githubusercontent.com/assets/15715378/12333574/f4691eec-bac2-11e5-8174-08400e376cf3.png)

**Comment by BetterToAutomateTheWorld** [comment]
The texture is great but i think players will have some difficulties to see correctly ingame the "?" and "!", but your idea is pretty good

**Comment by aerozoic** [comment]
This isn't really an issue. If it is then reopen it.
