### ISSUE TITLE
Add [u_skins]

### ISSUE THREAD

**Issue by ElementW** [MinetestForFun/server-minetestforfun-skyblock#60]
@Ombridride said to me on IRC players wanted skins.

So, give them skins.

Around 10 skins should do the work (at least 2 female), and since we want to keep the SB light, they have to be extremely optimized PNGs.
- [x] Add the mod
- [x] Make/add skins

**Comment by farfadet46** [comment]
hum, there is some skin in the 'wardrobe' (Sorry I don't know how to write it)

**Comment by BetterToAutomateTheWorld** [comment]
We need something simple, in the inventory :)
(Available when a player reach the level 2 for example)

Maybe we can hide or forbidden the u_skin button if a player without the level 2 done try to change skin, and display the button + chatmessage the player to inform him he can change his skin if he wants it with the inventory

**Comment by aerozoic** [comment]
Are you planning to use skins already made from a skin mod or make custom "skyblock" skins?

**Comment by ObaniGemini** [comment]
@cessna151 : maybe both :p
But first we need time and inspiration and some faith ^^

**Comment by Lymkwi** [comment]
https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/b1be52a2a14a6d6f2efe7c2483f99e9c31dba750
For now u_skins is quite heavy (not as much as Classic's version though). Since it comes with 160 skins, I added Classic's custom ones, and tweaked a few things in the code.
Now we should decide which skins to keep.

**Comment by ObaniGemini** [comment]
10 skins = 5 per page ?

**Comment by rredesigns** [comment]
I checked the skins. There's a lot of garbage there. I think there should be 2 skins for boys, 2 for girls, and 2 of fantasy and unisex  (e.g. zombie).

If somebody asks for more, you can add bit by bit, making sure that only is being added what is going to be used.

**Comment by Lymkwi** [comment]
By default, there are 16 skins per page. I think this is a good number.
@rredesigns You're free to remove everything and create your own skins, just remember to do the back and front previews, and fill in the meta files.

**Comment by rredesigns** [comment]
I'm talking about the number of skins rather than their aspect. They are a lot, the last pull I did downloaded over 5MB of textures. :/

**Comment by ObaniGemini** [comment]
we need between 10 and 20. @rredesigns if you want to find out the 10 or 20 best one, we'll make a selection and make some new ones if there are still bad skins in that selection. :smiley:

**Comment by rredesigns** [comment]
I'll check that later, I just gave a quick look to the massive download but didn't inspect the skins. I don't even know how to change the default one. How would players use them? Is there a HUD for picking a skin?

**Comment by ObaniGemini** [comment]
@rredesigns : yes, we will just add a new inventory_link to skins :)

**Comment by rredesigns** [comment]
Cool. :D 

I want a power ranger suit. :3

**Comment by aerozoic** [comment]
+1 for 2 male, 2 female, 2 fantasy. I think 6 is enough.

**Comment by BetterToAutomateTheWorld** [comment]
I agree with 2 male + 2 female + 2 unisex/fantasy
Need to make a list about the best skins now :)

**Comment by rredesigns** [comment]
I tried to delete some and totally broke the mod. I think Mg should handle this.

Best 10 are: Ironman, Link, female Link, soldier, Assassin's Creed char, one more girl(dunno the name), superman, another female, smoking guy, Storm Trooper.

**Comment by aerozoic** [comment]
@LeMagnesium i tried to revert but it failed. :confounded: The only commit that i intended to push is 276e022ca2b6340b37b3f57a1fd970f92b039486. The rest were not intended. :large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
Can you removed the submodule unified_inventory if you don't use it ?

**Comment by Lymkwi** [comment]
> Can you removed the submodule unified_inventory if you don't use it ?

It was just an accident. I fixed it : https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/8abafd005d7cbf418ce65872ff1b00bcfe9095bc
I also checked, u_skins works correctly ; @cessna151 : your only problem was the removal of u_inv. If you ask me, I can explain you how to update submodules or commit changes in them.

**Comment by aerozoic** [comment]
I optimized the preview textures only. If they don't look right let me know. The actual skin textures were already pretty small. I also fixed a strange mark that was on the face of character 8.   :small_orange_diamond:

**Comment by ghost** [comment]
@cessna151 the outline of the skin is white.
![u_skin](https://cloud.githubusercontent.com/assets/7189389/12596521/9f210b1c-c480-11e5-9988-3d208670f377.png)

**Comment by ElementW** [comment]
~~@crabman77 That's the same issue as MinetestForFun/server-minetestforfun#360~~

Nope, there's an actual outline. ~~Fixing it.~~

EDIT: just discovered the preview generation script is sh!t. Expected from me, really.

**Comment by aerozoic** [comment]
this is done, closed.

**Comment by Lymkwi** [comment]
I just edited the first comment to tick 'add/make skins', in case someone wonders why it's ticked.
