### ISSUE TITLE
New players are spawning in existing, protected nodes.

### ISSUE THREAD

**Issue by rredesigns** [MinetestForFun/server-minetestforfun-skyblock#61]
New players are spawning in existing, protected nodes.

**Comment by Lymkwi** [comment]
https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/b0abd39c6c88d815a517c3935c6855c25f1d4836
With this, we'll have a basic way of fooling the spawn system by asking multiple times for spawn positions, and retrying until we've got one isolated (or unloaded).

**Comment by BetterToAutomateTheWorld** [comment]
Good job @LeMagnesium 
Does it work on the dev server (or locally) without crash ?

**Comment by Lymkwi** [comment]
Yes it does. Whenever I push something that big I always check whether or not it works. (the rare cases when I don't check are hotfixes of a few characters that I manage to screw up)

**Comment by BetterToAutomateTheWorld** [comment]
Is this issue can be closed ? Have you checked ingame if it works properly ?

**Comment by Lymkwi** [comment]
This should be closed, now it works.

**Comment by BetterToAutomateTheWorld** [comment]
Seems to work, but I haven't any answers, I closed the issue, do not hesitate to reopen if problem subsists...

Thank you @LeMagnesium
