### ISSUE TITLE
"Report" countdown

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-skyblock#62]
We need a countdown for "Report" feature, players often spam us...
30min or 1 hour should be great in my point of view

PS : Don't forget to apply it to all of our servers

**Comment by aerozoic** [comment]
I suggest starting it lower at about 1 to 5 minutes, then if we still get spammed, increase it a little. If a player has a legitimate report but think they need to split it up because it is too long, or they just like to /report for each line, then they'll be prevented from giving the full report if the timer is too high.

**Comment by rredesigns** [comment]
Cessna has a good point. But usually, a report should be short. Concise and precise. So no. :p

**Comment by rredesigns** [comment]
I think we should actually limit it to one report per session. It will be easier to keep track (just create a file in the server after first report that remains untill player logs off) and also easier to code. Plus, no much load to the server, since the second report would check for that file. No timer.

**Comment by ghost** [comment]
What? this commit has removed countdown https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/633fbc3b79482ae04ea8c0d1de851f28b70d41fc

**Comment by BetterToAutomateTheWorld** [comment]
Yes, this commit erase the 10 minutes countdown... But the countdown wasn't commented...

So, can someone re-add the "report" countdown and comment the code ?

Let's try with 5minutes (300 seconds)
(PS : I don't see a chatmessage to inform players he tried to send a message during the countdown, if it's not implemented, it will be a good idea to add it)

**Comment by aerozoic** [comment]
I only receive reports to my inbox if i am actually in game. Reports that are sent when i'm offline do not go to my inbox. Is this the way it was intended?

**Comment by BetterToAutomateTheWorld** [comment]
I will prefer you receive the inbox when you're online and offline, it's more interesting like this.

I checked my inbox yesterday, 104 messages, many spams, less than 10 messages was really reports...

We **REALLY** need the countdown to be re-inplemented ! @gravgun

**Comment by aerozoic** [comment]
@Ombridride i know why we get spammed. If you click the report button in inventory and then type a message and click send, nothing appears to happen, the message is still there and there is no notification until you close the inventory. But when nothing happens the natural response is to click the send button again and again and each time the message gets sent again.

**Comment by BetterToAutomateTheWorld** [comment]
Ok, need to solve this point...

**Comment by BetterToAutomateTheWorld** [comment]
First, @gravgun can you re-add the countdown lines ?
Second, someone can add a chat message for validate the report sending to moderators/administrators after a player sended a report message ? @gravgun or @LeMagnesium

**Comment by aerozoic** [comment]
A chat message can't be seen when using the report button from inventory. Also i think a chat message is already a feature. 
Edit: Unless you meant add a msg if the countdown hasn't finished. That is needed.

**Comment by aerozoic** [comment]
If the report message can be deleted from the input box after it is sent, that would be helpful to indicate that it was sent.

**Comment by Lymkwi** [comment]
> If the report message can be deleted from the input box after it is sent, that would be helpful to indicate that it was sent.

I'm gonna do that too then.

**Comment by Lymkwi** [comment]
There you go.
https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/d1f1a3b8722dce03cec7ef53034d67f4412f587b
