### ISSUE TITLE
Fork [unified_inventory]?

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#63]
With bags already disabled, forking will allow us to disable bags.lua for two reasons:

First, to remove the craft items. Second, and more importantly, to reduce bandwidth use.

R_R_E_Designs confirmed it is using bandwidth by doing some traffic analysis.

**Comment by BetterToAutomateTheWorld** [comment]
Our version of [unified_inventory] is already a fork

Indeed, we need to remove all code/lines about bags.lua and its formspec/inventory window/craft/etc... If it's currently just "hidden"

**Comment by rredesigns** [comment]
I guess I can try it while gravgun is away. I'll take a look at it.

**Comment by ElementW** [comment]
@rredesigns @gravgun may be away but he is always watching.

**Comment by rredesigns** [comment]
He's always pushing bugs. XD

**Comment by rredesigns** [comment]
Ombridride, I think I have it. I can't test locally so a merge is needed. Where is that forked repo for the mod?

**Comment by Lymkwi** [comment]
Our version is _not_ a fork. It's directly hooked to Upstream.
I just forked minetest-technic's repository though, there it is : https://github.com/MinetestForFun/unified_inventory .

**Comment by aerozoic** [comment]
this is done, closed

**Comment by BetterToAutomateTheWorld** [comment]
yes, thank you for your work @cessna151

**Comment by aerozoic** [comment]
@LeMagnesium actually did the work :smile: 
:small_orange_diamond:
