### ISSUE TITLE
Strange bug ?

### ISSUE THREAD

**Issue by ObaniGemini** [MinetestForFun/server-minetestforfun-skyblock#65]
`<MFFSB-Bot> araba completed the quest "place_door" on level 1
<MFFSB-Bot> araba completed the quest "place_door" on level 1
<MFFSB-Bot> araba completed the quest "place_door" on level 1
<MFFSB-Bot> araba completed the quest "place_door" on level 1
<MFFSB-Bot> araba completed the quest "place_door" on level 1
<MFFSB-Bot> araba completed the quest "place_door" on level 1
<MFFSB-Bot> araba completed the quest "place_door" on level 1
<MFFSB-Bot> araba completed the quest "place_door" on level 1
<MFFSB-Bot> araba completed the quest "place_door" on level 1
<MFFSB-Bot> araba completed the quest "place_door" on level 1
<MFFSB-Bot> araba completed the quest "place_door" on level 1
<MFFSB-Bot> araba completed the quest "place_door" on level 1
<MFFSB-Bot> araba completed the quest "place_door" on level 1
<MFFSB-Bot> araba completed the quest "place_door" on level 1
<MFFSB-Bot> araba completed the quest "place_door" on level 1
<MFFSB-Bot> araba completed the quest "place_door" on level 1` ( [17:00:23] to [17:04:48] )

`<MFFSB-Bot> araba completed the quest "place_sign" on level 1
<MFFSB-Bot> araba completed the quest "place_sign" on level 1
<MFFSB-Bot> araba completed the quest "place_sign" on level 1
<MFFSB-Bot> araba completed the quest "place_sign" on level 1
<MFFSB-Bot> araba completed the quest "place_sign" on level 1
<MFFSB-Bot> araba completed the quest "place_sign" on level 1
<MFFSB-Bot> araba completed the quest "place_sign" on level 1
<MFFSB-Bot> araba completed the quest "place_sign" on level 1
<MFFSB-Bot> araba completed the quest "place_sign" on level 1
<MFFSB-Bot> araba completed the quest "place_sign" on level 1
<MFFSB-Bot> araba completed the quest "place_sign" on level 1` ( [16:55:25] to [16:58:24] )

**WTF happened ?**

**Comment by Lymkwi** [comment]
They probably died. That's what happens usually.

**Comment by ObaniGemini** [comment]
@LeMagnesium : he spam died during 4 minutes ? And still could do the same quest in the middle of the level 1 ? This is strange IMO.

**Comment by Lymkwi** [comment]
This could be so many things except a bug. If they had ressources stacked in a chest dying is not an issue.
Still, until you've proven there was something wrong, based on the chat, it could totally happen without any bug involved.

**Comment by aerozoic** [comment]
I have seen this recently as well, and it was within just a few seconds, although i can't say whether it's a bug.

**Comment by BetterToAutomateTheWorld** [comment]
Probably not a bug in my point of view, just a player which repeat the quest after he died...

**Comment by BetterToAutomateTheWorld** [comment]
I closed the issue because of my last answer.

**Comment by ObaniGemini** [comment]
I think I can confirm that. They're is more than one minute between each quest done. Players should learn to play...

**Comment by ElementW** [comment]
@ObaniGemini Players should mostly learn that Minetest is completely unplayable on a tablet.

Actually, it's also kind of unplayable (CPU hog) on PC too...

**Comment by BetterToAutomateTheWorld** [comment]
+10 @gravgun

**Comment by aerozoic** [comment]
@gravgun? i thought it played quite well on my 10 year old laptop PC before my graphics gave up.

**Comment by ElementW** [comment]
@cessna151 The weird thing about it is that its CPU consumption, as well as graphics load, increases exponentially with CPU power. I.e. it **really** runs better on old computers than on recent ones.

**Comment by aerozoic** [comment]
LOL, figures.  :small_orange_diamond:
