### ISSUE TITLE
Give time privilege to repo owners and maybe other people ?

### ISSUE THREAD

**Issue by ObaniGemini** [MinetestForFun/server-minetestforfun-skyblock#66]
We, workers on the repositories of Xorhub, need the `time` privilege for the skyblock server. We also need tokens to login on IRC. I think that if we are abled to push here, it's that we are trustworthy, and that we will not abuse of it, or annoy other players before using it.

It's a top priority because many players are annoyed by night, but not every player. So we need to have people to moderate time on the server. It also is annoying because of some players with a limited bandwitch (like @cessna151 ) are not abled to play too much and can't really build at night.

So those players need `time` privilege :
- @cessna151 ( cessna151 )
- @Cyberpangolin ( Cyberpangolin )
- @gravgun ( gravgun )
- @LeMagnesium ( Mg )
- @crabman77 ( crabman)
- @fabienwang ( fabienwang )
- @rredesigns ( R_R_E_Designs )
- @Ataron ( Ataron )
- @ObaniGemini ( Obani )

Maybe also :
- JAPP ?
- Uraza ?
- LizzardBeth ?

**Comment by rredesigns** [comment]
I agree. 

+1 to LizzardBeth (don't know her, but she's online quite often)

**Comment by aerozoic** [comment]
+1 for time priv

@ObaniGemini you can use /gen_token in game to get your IRC login token :-)

**Comment by BetterToAutomateTheWorld** [comment]
If i understand well, the night is a problem for all players ?
If yes, we can easily erase the night

**Comment by ElementW** [comment]
@Ombridride "If yes, we can easily erase the night" if you do you'd fuck up 50% of the plans I had for SB.

**Comment by rredesigns** [comment]
@Ombridride not for all players, but for most. Especially the new ones who happen to either spawn at night or reach the night without at least a torch.

**Comment by ObaniGemini** [comment]
@Ombridride not for all players, that's why we don't give that clock item @rredesigns . As @gravgun said, night can still be important to players. But as many need to be at day, a moderation system should be added. Here is the point.

**Comment by rredesigns** [comment]
I understand the point. I just explained that the night was not an issue for everyone.

Erasing the night is out of discussion, night can be cool, but if most players agree that they want to skip it, it would be great to do it without having to coordinate a bunch of kids that won't listen. XD

**Comment by BetterToAutomateTheWorld** [comment]
@gravgun will introduce special night nodes at the end of this week, and he explains me "night is really important in his future ideas" so, we won't erase night BUT we will reduce surely the night proportionality for something like 1/3 or 1/4 of night in a day and not the currently 1/2 night in a day.

**Comment by Lymkwi** [comment]
> we will reduce surely the night proportionality for something like 1/3 or 1/4 of night in a day and not the currently 1/2 night in a day.

How are we supposed to do that without fiddling in the engine exactly?

**Comment by ElementW** [comment]
@LeMagnesium The day/night cycle speed can be dynamically controlled through a server setting. An easy solution is to periodically check for time of day, and if within the night, set that timescale higher.

**Comment by rredesigns** [comment]
Sounds like unnecessary work, for modders and for the server. Is much easier to just allow us to set time.

**Comment by BetterToAutomateTheWorld** [comment]
Reduce the night duration is a great idea, it's not heavy, and its integration to the SB server is easy (already done, some topics discuss about it in the forum)

**Comment by BetterToAutomateTheWorld** [comment]
The time privilege item won't be given, we will prefer a shorter night system based.

I closed this issue.
