### ISSUE TITLE
Area mod

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-skyblock#7]
We need to add an area mod, wich one ? the MFF one ? tweaked for how many areas ?

Is it already in the engine ?

Or maybe our island is already protected ?

**Comment by Lymkwi** [comment]
[Protector](https://github.com/MinetestForFun/server-minetestforfun-skyblock/tree/master/mods/protector) is already there (and there's a bucket-grief prevention system).

**Comment by BetterToAutomateTheWorld** [comment]
Indeed, I experimented it !

The protector node :
![node](http://i.imgur.com/1ZhU139.png)

Its menu (well done !) :
![menu](http://i.imgur.com/fCSnW0L.png)
