### ISSUE TITLE
Max button bugs

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-skyblock#70]
`Max button creates oversized stacks.
But that stack is only existent in the inv.
Once you place them, the engine knows a stack can't be bigger than 99
So it deletes all up to 99.`

2 complains about corrupted inventory, maybe because of Max Button
`minetestforfun, ihatedrift has the same bug i had yesterday with his inventory`

**Comment by rredesigns** [comment]
Max button creates buggy stacks, but that seems not to be the issue.

**Comment by Lymkwi** [comment]
I'm going to put a limit on the size of produced stacks.
