### ISSUE TITLE
u_skin bug

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-skyblock#71]
`ihatedrift : AND ALSO THIS MORNING WHEN I CAME ON I HAD A GIRL SKIN NOT THE SKIN I USED BEFOR`

Apparently, the skin isn't saved when you disconnect/reconnect ? or it's due to the u_skin multiple updates which erase skins from the list ?

**Comment by rredesigns** [comment]
No. This was due to the latest changes to the mod. Since the skins has to be renumbered, he just got a different skin with the number of the previous pack. (number was reduced from 15 skins to 8 in last commit)

No bug here. You can close this issue.

**Comment by BetterToAutomateTheWorld** [comment]
Yes, this is what i'm thinking about
Thank you, for the information
