### ISSUE TITLE
x_decor bug

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-skyblock#72]
It's maybe a name string problem

The skyblock tools (pickaxe, axe, etc..) can't be enchanted.

don't forgot to comment you lines if you fix it.

Related : @kilbith

**Comment by kilbith** [comment]
Quels outils as-tu essayé d'enchanter très exactement ?

S'ils ne sont pas supportés, ajoute-les ici : https://github.com/kilbith/xdecor/blob/master/enchanting.lua#L130

N.B. la copie de `xdecor` que tu utilises dans ton jeu est vieille de 22 jours.

**Comment by aerozoic** [comment]
I don't see any problems. I can enchant tools just fine.

**Comment by Lymkwi** [comment]
There, it's updated. I'll test the enchant.
https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/910461344ab4547c0d14cebd1e1ba9fde1ccc7fb

By the way we couldn't fix it on our own, @Ombridride, since it's a submodule of upstream.

**Comment by BetterToAutomateTheWorld** [comment]
@cessna151 can you check with ihatedrift and see if he still have the problem ?

@kilbith thank you for the infomation

@LeMagnesium Why did we haven't this mod up to date if it's a submodule of the official repository, it's not normal... ?

**Comment by Lymkwi** [comment]
> Why didn't we have this mod up to date if it's a submodule of the official repository

I've only been aware of xdecor being on Sb, moreover in the form of a submodule, since I tried to update it manually 2 days ago ; so I didn't think of updating it.

**Comment by aerozoic** [comment]
ihatedrift says everything is fine now.

**Comment by BetterToAutomateTheWorld** [comment]
Fixed.
