### ISSUE TITLE
REDIS is bugged again

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#73]
@Ombridride Just like this morning, as soon as i leave and come back, everything i placed is gone. This time i only lost about 5 stacks of cobble. :unamused:

**Comment by BetterToAutomateTheWorld** [comment]
I answered you on the IRC "later tell", I will investigate the logs, but it's maybe the daily reboot

**Comment by aerozoic** [comment]
This happened again last night at about the same time as the night before; approximately 2 hours before the nightly server reboot.

**Comment by BetterToAutomateTheWorld** [comment]
Daily reboot is at 4:32AM, so it was at ~2:30AM ? (UTC +1)

**Comment by aerozoic** [comment]
@Ombridride yes that is correct. It also happened again about 30 minutes ago. 9PM (utc +1)

**Comment by ElementW** [comment]
Bug likely comes from the `mtsatellite` toolkit itself. See https://bitbucket.org/s_l_teichmann/mtsatellite/issues/15/more-than-one-mtsatellite-on-the-same

**Comment by aerozoic** [comment]
Happened again at about 3AM server time. (30 minutes ago)

**Comment by BetterToAutomateTheWorld** [comment]
@gravgun did you rollback the mtsatellite version ?

**Comment by ElementW** [comment]
@Ombridride Yes I did and nothing changed.

**Comment by BetterToAutomateTheWorld** [comment]
Strange, the problem is only on SkyBlock server...
We miss something

**Comment by aerozoic** [comment]
@Ombridride I suggest disable REDIS and revert back to previous DB method temporarily until the bug can be fixed properly.

**Comment by BetterToAutomateTheWorld** [comment]
The latest feature(/fix) we implemanted doesn't work in crontab but work in our script, @gravgun is testing a way to do it with a script launched by the crontab, in test on the HG currently, it will be on all servers soon, just be patient :)

**Comment by ElementW** [comment]
@Ombridride "it will be on all servers soon" It already is, I just updated the crontab minutes ago. I guarantee it works.

**Comment by BetterToAutomateTheWorld** [comment]
REDIS backend isn't bugged anymore :)

For proof, the last freeze was on 29/01/2015 :
![last_freeze_redis](http://i.imgur.com/p8AEiDW.png)

I closed the issue.
