### ISSUE TITLE
Bug with buckets and cauldrons

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-skyblock#74]
Linked to https://github.com/kilbith/xdecor/issues/23#issuecomment-174570292

**Comment by Lymkwi** [comment]
All of this is based on our overrides of on_use. There are many across the repository. I'll investigate.

**Comment by BetterToAutomateTheWorld** [comment]
@LeMagnesium can you check this issue please ?

**Comment by Lymkwi** [comment]
There, just a 'blind' callback not calling other callbacks : https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/74908a69e25336a7ab66f9f3da5a6e82f43a20b2

**Comment by BetterToAutomateTheWorld** [comment]
@cornernote I think it would interest you

Thank you for the fix Mg

**Comment by cornernote** [comment]
Thanks for the fix @LeMagnesium, have applied it here:
https://github.com/cornernote/minetest-skyblock/commit/73d5e150fe984c1c066c2d60fbbf26e5df6588e2
