### ISSUE TITLE
Shorter night compared to day

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-skyblock#75]
Already talked here https://github.com/MinetestForFun/server-minetestforfun-skyblock/issues/66 and here https://github.com/MinetestForFun/server-minetestforfun-skyblock/issues/64

The idea is to make the night shorter, if we want to code it, we just need to add time on the nights times.

Actually it's 50% day & 50% night, first we will try 33% night & 66% day.

**Comment by Lymkwi** [comment]
There you go.
https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/ff267d62ee729bfd0ea6d50ea77215b6f5121e90

**Comment by BetterToAutomateTheWorld** [comment]
Ok perfect, good implementation ! :+1: 

Before closed this issue, can you :
- [x] Add this mod in **submodule**
- [X] Add it also on the **Creative** and **Classic** servers => https://github.com/MinetestForFun/server-minetestforfun/commit/2ab52cc037ad64b0153ed985cc6b6696a9cdb70a https://github.com/MinetestForFun/server-minetestforfun-creative/commit/fe63e264c03ba5442961c91847cc058cff7f8157
- [X] You will need to tweak a little the Minetest.conf also, use the mods section for this purpose => https://github.com/MinetestForFun/server-minetestforfun/commit/2ab52cc037ad64b0153ed985cc6b6696a9cdb70a https://github.com/MinetestForFun/server-minetestforfun-creative/commit/fe63e264c03ba5442961c91847cc058cff7f8157

You can also post it on the Minetest forum if you think it's needed (in my point of view it will be a good thing, because no mods actually do this in the forum)

**Comment by ObaniGemini** [comment]
Why should we add this mod to creative ? There are not many players on creative so it's not a problem to  pass the night

**Comment by Lymkwi** [comment]
I could see why you would want to add it on creative even though, as @ObaniGemini pointed out, the number of players there usually is low enough to ask everyone to sleep ; but okay, why not.
But then, why classic? Do you want to increase the night ratio? Is either one of day and night more dangerous?

**Comment by BetterToAutomateTheWorld** [comment]
If it's on classic else it's on creative.

In this purpose, we will need a merge from classic to creative soon because the creative server miss (sadly) some features we don't merge systematically when we work on classic => will be a future task

It will be on classic because tweak the night/day ratio should be interesting for events/seasons/or other goals, and because the mod is easily disable if we don't need it anymore finally, the Mg's mod is also really light, an another good point which sounds good

**Comment by BetterToAutomateTheWorld** [comment]
Applied on the Skyblock server, need reviews/tests if it works or not :)

**Comment by Lymkwi** [comment]
https://github.com/MinetestForFun/server-minetestforfun/commit/2ab52cc037ad64b0153ed985cc6b6696a9cdb70a
https://github.com/MinetestForFun/server-minetestforfun-creative/commit/fe63e264c03ba5442961c91847cc058cff7f8157
I think you can now check if everything is okay and close the issue.

**Comment by aerozoic** [comment]
According to the time stamps in the server log, day lasts 19 minutes and night lasts 13. That's a 60/40 split so it's working.

**Comment by BetterToAutomateTheWorld** [comment]
Are you sure it's 60/40 ? The actual time stamps should be 66/33

Minetest.conf configuration :

```
### Day/Night Ratio ###
#######################
day_time_ratio = 66.7
night_time_ratio = 33.3
```

**Comment by aerozoic** [comment]
#### Fun with spreadsheets...

From the Skyblock log...

> 2016-02-23 13:01:35: ACTION[ServerThread]: [TimeRegulation] Entering day period : time_speed 44.977511244378
> 2016-02-23 13:20:30: ACTION[ServerThread]: [TimeRegulation] Entering night period : time_speed 90.09009009009
> 2016-02-23 13:33:23: ACTION[ServerThread]: [TimeRegulation] Entering day period : time_speed 44.977511244378
> 2016-02-23 13:52:21: ACTION[ServerThread]: [TimeRegulation] Entering night period : time_speed 90.09009009009
> 2016-02-23 14:05:53: ACTION[ServerThread]: [TimeRegulation] Entering day period : time_speed 44.977511244378
> 2016-02-23 14:24:08: ACTION[ServerThread]: [TimeRegulation] Entering night period : time_speed 90.09009009009
> 2016-02-23 14:37:41: ACTION[ServerThread]: [TimeRegulation] Entering day period : time_speed 44.977511244378
> 2016-02-23 14:56:41: ACTION[ServerThread]: [TimeRegulation] Entering night period : time_speed 90.09009009009
> 2016-02-23 15:09:33: ACTION[ServerThread]: [TimeRegulation] Entering day period : time_speed 44.977511244378
> 2016-02-23 15:28:29: ACTION[ServerThread]: [TimeRegulation] Entering night period : time_speed 
> 90.09009009009
> 2016-02-23 15:42:03: ACTION[ServerThread]: [TimeRegulation] Entering day period : time_speed 44.977511244378

| TIME STAMP |  | LENGTH |  | Average Day |
| :-: | :-: | :-: | :-: | :-: |
| 13:01:35 |  | 0:18:55 |  | 0:18:49 |
| 13:20:30 |  | 0:12:53 |  |  |
| 13:33:23 |  | 0:18:58 |  | **Average Night** |
| 13:52:21 |  | 0:13:32 |  | 0:13:17 |
| 14:05:53 |  | 0:18:15 |  |  |
| 14:24:08 |  | 0:13:33 |  | **Average day/night Cycle** |
| 14:37:41 |  | 0:19:00 |  | 0:32:06 |
| 14:56:41 |  | 0:12:52 |  |  |
| 15:09:33 |  | 0:18:56 |  | **Day Ratio** |
| 15:28:29 |  | 0:13:34 |  | 58.6% |
| 15:42:03 |  |  |  |  |
|  |  |  |  | **Night Ratio** |
|  |  |  |  | 41.4% |

:large_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
Curiously the timestanp isn't linear and didn't seems to be equal to the "minetest.conf" values
@LeMagnesium can you explain us this defect ?

**Comment by Lymkwi** [comment]
> @LeMagnesium can you explain us this defect ?

Basic inacurracy of the engine and my loop. I cannot have a loop running once every second, it would be insane. I could shorten the interval though.

**Comment by BetterToAutomateTheWorld** [comment]
Ok, thank you for the additional informations

No need to shorten the interval, it's great like this.

I closed the issue, it's done. Good job !
