### ISSUE TITLE
Furnace bugged now

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-skyblock#77]
Since the last commit of the "furnace" mod for the cooking when players aren't near they furnace, we encounter a big bug :
- furnace cook 30 per 30 nodes each "tick"

@ElementW, can you fix your commit please ?

**Comment by ElementW** [comment]
Ayy, reverting. 490420b

See why I'm pissed? Even a fix commit is dead bad. People never learn discrete computation is the bane of anything that can be paused.

31db4ca542b727374ef30580f65a4d5e1a8285aa introduces sofar's attempt.

**Comment by BetterToAutomateTheWorld** [comment]
Ok, thank you, i agree with your reverting ;p

The best thing to do next to this revert is to merge & reboot the server, can you do it please ?

**Comment by aerozoic** [comment]
I'm available right now for testing. @Ombridride If you go ahead and do it, i'll test.
