### ISSUE TITLE
Protector bug

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#78]
This only applies to the normal protector logo, not the blocks or the 3x protectors, just the normal protector logos(protector:protect2).

Logos currently **cannot** be removed. When attempting to dig them an "Unknown Object" texture appears next to it and the logo remains. 

I copied this error from the server log right after i found this bug:
2016-02-12 21:41:41: ERROR[ServerThread]: LuaEntity name "protector:display" not defined
:small_orange_diamond:

**Comment by BetterToAutomateTheWorld** [comment]
@ElementW can you fix this issue please ?

**Comment by ElementW** [comment]
Tell that to Mr. Somebody who rebased my work on commits fixing things I've already fixed.

Also, you'll notice I can't fix anything any more. Farewell.

**Comment by Lymkwi** [comment]
> Tell that to Mr. Somebody who rebased my work on commits fixing things I've already fixed.

I get it I messed up somewhere. Rebasing something you haven't coded yourself is not that easy. (Also I showed you a diff before committing)
And finally, this seems to be fixing the issue : https://github.com/MinetestForFun/protector/commit/35b7df3d1a6cc7e17c9c0a766da67ef71e891310. So still thanks to @ElementW for fixing my sh*t.
