### ISSUE TITLE
recent Xdecor update regarding mese

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#79]
I just noticed mese blocks/lamps can no longer be cut with the worktable and all mese block/lamp nodes created with the worktable (e.g. microslabs/nanoslabs/cubes etc...) and placed on the map are now unknown node textures. This is a terrible update in my opinion. I'd like to see this update reversed.

**Comment by Lymkwi** [comment]
If we modify xdecor then we have to fork it.

**Comment by aerozoic** [comment]
@LeMagnesium i get the following error when trying to update the xdecor submodule: 
fatal: reference is not a tree: f9e52c0ca5dc3af357dea3bcdc46f8a1d56c2ac1
Unable to checkout 'f9e52c0ca5dc3af357dea3bcdc46f8a1d56c2ac1' in submodule path 'mods/xdecor'

**Comment by aerozoic** [comment]
The .gitmodules file still points to kilbith's repo. Is that the problem?

**Comment by Lymkwi** [comment]
It might be, yes. Submodules work in a weird fashion. Trying to change the .gitmodules file could fix the issue.
