### ISSUE TITLE
[xdecor] worktable nano slab

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#82]
Several, but not all, blocks in the worktable shows an unknown item for the nano slab.

Edit: tested so far... Obsidian, Runestone, Steel block, Hard Clay, and Stone all produce unknown item for nano slab. Brick, Mese lamp, and Desert stone brick work normal.

**Comment by BetterToAutomateTheWorld** [comment]
Thank you for the report.

We need to investigate why this bug occurred...

As always with the well done [xdecor] mod, maybe @kilbith can give you his lights ?

**Comment by kilbith** [comment]
No idea, everything is fine on my side after checking.

**Comment by BetterToAutomateTheWorld** [comment]
**other** unknow nodes :
![prison doors](http://i.imgur.com/t5U31lG.jpg)

**Comment by kilbith** [comment]
Oui ça c'est une ancienne porte de prison, pas un nanoslab.

Assure-toi que les alias que j'ai récemment ajouté sont bien mis en oeuvre.

**Comment by Lymkwi** [comment]
Il s'agissait en fait d'un problème de mise à jour de submodules. Tout est rentré dans l'ordre

**Comment by BetterToAutomateTheWorld** [comment]
Prison doors aren't a problem anymore
![prison_good](http://i.imgur.com/cLYB506.png)

But stone rune slab still be unknow...
![unknow_slab_stone_rune](http://i.imgur.com/UXYxrBP.png)

**Comment by kilbith** [comment]
Vraiment étrange, j'ai pourtant bien ce nanoslab de mon côté : 

![screenshot_20160229_222139](https://cloud.githubusercontent.com/assets/7883281/13409397/28a15bc2-df33-11e5-8f30-ecf936a853c1.png)

**Comment by kilbith** [comment]
Pour info j'ai installé MFF-Skyblock de mon côté et essayé de couper quelques blocs. J'ai pas été capable de reproduire ce bug, tout était normal.

Est-ce que LuaJIT est utilisé par hasard ?

**Comment by BetterToAutomateTheWorld** [comment]
@kilbith Oui, LuaJIT est utilisé (version assez vieillot actuellement, j'upgrade en Debian Jessie 8.3 bientot)
`LuaJIT 2.0.3 -- Copyright (C) 2005-2014 Mike Pall. http://luajit.org/`

**Comment by kilbith** [comment]
OK, alors tant mieux.

**Comment by BetterToAutomateTheWorld** [comment]
Pourrais-tu expliquer ce qui ferait que LuaJIT aurait un impacte sur nos soucis d'unknow nodes ?

**Comment by kilbith** [comment]
En fait le code itère à travers tous les blocs enregistrés au démarrage pour déterminer lesquels choisir pour couper. Donc si t'as beaucoup de blocs enregistrés et que tu n'utilises pas LuaJIT, il est possible que cela cause quelques anomalies à cause de la lenteur de Lua sur un tel traitement.

Mais c'est juste une supposition.

**Comment by kilbith** [comment]
Pouvez-vous mettre à jour `xdecor` et bien vérifier si ce bug est résolu, svp ?

Un autre serveur a appliqué mon dernier patch et apparemment ça a résolu le problème...

**Comment by kilbith** [comment]
@LeMagnesium J'aurais préféré avoir une confirmation avant de fermer ce ticket.

**Comment by Lymkwi** [comment]
@kilbith Je n'avais pas pensé que cela le fermerait, attends..
EDIT: Voilà

**Comment by BetterToAutomateTheWorld** [comment]
Ok, suite au dernier merge nous n'avons plus de problème sur les nano slab, merci pour votre suivi, je ferme le ticket.
