### ISSUE TITLE
Furnace fast cooks

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#83]
The furnace cooks fast, not instant, but much faster than normal.

**Comment by BetterToAutomateTheWorld** [comment]
Please, someone can check our latest furnaces changes and point out the bugged lines ? we need to fix it as soon as possible ...
( @crabman77 @LeMagnesium )

**Comment by Lymkwi** [comment]
The mechanism for furnaces was updated, I think. It uses NodeTimers now. (more accurate, presumably, and embedded inside each node)

**Comment by BetterToAutomateTheWorld** [comment]
You need to be sure, can you link us a piece of code that prove what you figured out ?
If the cooking time is a little faster, it's not a problem in my point of view (it's a building server after all)

If the cooking time is instant, it's a bug yes, but it's not the case, didn't it ?

**Comment by aerozoic** [comment]
I just timed it... 15 seconds to cook a 99 stack of dirt.

**Comment by BetterToAutomateTheWorld** [comment]
Wow, it's really fast, too fast ...

Before, the dirt was cooking in 2sec, so now in less than 0,2sec, this is not great, we need to fix it

Thank you for the details

**Comment by Lymkwi** [comment]
Well [this](https://github.com/MinetestForFun/server-minetestforfun-skyblock/blob/master/mods/default/furnace.lua#L102) and [that](https://github.com/MinetestForFun/server-minetestforfun-skyblock/blob/master/mods/default/furnace.lua#L274) will clearly explain why I think it's now in a node timer.

As far as I can read the code, for the amount of seconds elapsed inbetween two calls to the node_timer callback, the latter will try to compensate the amount of cooking it should have done if it were running constantly. It's... not very stupid.. but hard to tweak..
However, we could add values in `skyblock_levels/register_craft.lua` for each cooking craft recipe to specify a cooktime (the default value might be too low).

**Comment by Lymkwi** [comment]
The issue was somehow fixed by updating to Minetest Game's current furnace code... should we keep this open?

**Comment by ObaniGemini** [comment]
@LeMagnesium : it's because there is not the "working when chunk unloaded" feature. The commit I made was from a PR using ABMs and the furnace converted to Node Timers. We could maybe correct it by taking a look at this https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/a7ad78136f5ecb515b8deef15d12bb007261764f

**Comment by BetterToAutomateTheWorld** [comment]
This issue is fixed since this commit https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/622c13e20f239cdecfc9fcfb887645bc8c08cc15

Sorry we didn't update this issue after the commit

I closed the issue.
