### ISSUE TITLE
Doors ignore protection

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#84]
Doors can be placed in other's protected areas. I tested this with japanese doors and glass doors.

**Comment by BetterToAutomateTheWorld** [comment]
New Doors API/protector problem, need to upstream this to :
- @tenplus1 (protector)
- @sofar & @paramat (new doors API)

**Comment by Lymkwi** [comment]
Japanese doors belong to xdecor as far as I remember, and the update I did on doors yesterday should have introduced a protection check.

**Comment by Lymkwi** [comment]
After running tests on local it's impossible to place any of the available doors in an area you do not have access to. I also checked on chlorine, with the same outcome.

**Comment by sofar** [comment]
The problem was fixed upstream in 

https://github.com/minetest/minetest_game/commit/00a0d9a5d4bda9a3a33d1992218c3e8094559730

**Comment by aerozoic** [comment]
Confirmed on SB server itself, it's fixed.
