### ISSUE TITLE
[xdecor] craft guide item

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#85]
When using the craft guide item (made with a book and blue dye) if you press the "X" (reset) button for the search input, the window flashes to the Inbox window and all messages are deleted.

**Comment by ObaniGemini** [comment]
There are two craft guides actually if I got it well...
So maybe should we remove Xdecor's one ? or fix it and remove the other one ?

**Comment by Lymkwi** [comment]
If the window flashes then something went wrong. I have no clue how you could bind a key press to a function in Minetest's API but if it's triggered by pressing X then the engine might be partially responsible.
EDIT: Lucky you, there is an update of xdecor's craft guide.

**Comment by ObaniGemini** [comment]
@LeMagnesium : https://github.com/minetest/minetest/pull/2445 ...

**Comment by kilbith** [comment]
Il parle du bouton de formspec "X", pas la touche X du clavier.

Y'avait un conflit entre les 2 mods. C'est ma faute, j'ai réparé ça : https://github.com/kilbith/xdecor/commit/c804c26cd9565906e27ae697a3eede46f481b90f

**Comment by BetterToAutomateTheWorld** [comment]
Ah, bien vu @kilbith !
Merci pour le fix, on va le merger ASAP

**Comment by aerozoic** [comment]
Even after the update this issue still persists. It still does the same thing.

**Comment by BetterToAutomateTheWorld** [comment]
Yes, I tested it, the bug is still here

**Comment by kilbith** [comment]
En fait il manque une petite vérification dans votre mod `email`.

Les deux mods ont `fields.clear` en commun (provoquant un conflit), ce qui veut dire que vous devez vérifier que c'est bien le nom de formspec `email:inbox` d'où les champs doivent être traités, et pas les formspecs extérieurs.

Essayez d'ajouter le code suivant au-dessus de [cette ligne](https://github.com/MinetestForFun/server-minetestforfun-skyblock/blob/master/mods/email/init.lua#L140) : 

``` Lua
if formname ~= "email:inbox" then return end
```

**Comment by Lymkwi** [comment]
By @crabman77 : https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/daa2c56e526e65477c7076d6cc5e6e5846b67649

**Comment by BetterToAutomateTheWorld** [comment]
Someone can try the fix ? I just merged the Skyblock server

**Comment by ghost** [comment]
testé en local, en commentant le fix pour voir et c'est ok. Sans le fix on a le formspec des email qui s'affiche à la place du craft guide.

**Comment by BetterToAutomateTheWorld** [comment]
Parfait, je ferme.
