### ISSUE TITLE
[xdecor] Cauldron

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#86]
I can put water in and boil it but i can't put food in it.

EDIT: No response after dropping food in it.

**Comment by aerozoic** [comment]
Further info... Testing locally with an upstream copy of xdecor in singleplayer mode, i discovered how to correctly use the cauldron but i can not make it work on skyblock. When i drop the food in nothing happens.

**Comment by Lymkwi** [comment]
(I just love how some mods decide to rebel and have bugs all of a sudden)
I'm just curious, how did you manage to boil the water considering there isn't a single item which itemstring contains "fire" in skyblock?

**Comment by BetterToAutomateTheWorld** [comment]
Hi,

Thanks to @LeMagnesium !

Cauldrons debugged since this commit https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/63b48f9bb06e5cc2c840df28ac315c7cffe013bf

I added a random message https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/5849331fec963043b514d883fac8197e0f984b53

I closed the issue.

**Comment by aerozoic** [comment]
I just used flint and steel to make a fire under it to make the water boil.

**Comment by BetterToAutomateTheWorld** [comment]
Ok, so the fakefire from the flint&steel mod have the "fire" group ?
@LeMagnesium can you confirm ?

if it's yes, someone can fix the random message ?

**Comment by aerozoic** [comment]
Assuming the server was rebooted, the cauldron still won't respond to food dropped in it. I've confirmed this testing locally as well.

**Comment by Lymkwi** [comment]
You need :
- To place a torch under the cauldron and wait until it has boiling water in it
- Throw in 2 foods (apple, bread, etc)

The code updated properly on the server, I just checked it, it works.

**Comment by aerozoic** [comment]
Well i tried again and still nothing so i tried it with two apples and it worked. So it doesn't work with the farming crops.

**Comment by BetterToAutomateTheWorld** [comment]
I tried it and it works with 2 apples

Small guide :
1) put your cauldron
2) put (with a water bucket) water inside the cauldron
3) put a torch under the cauldron (OR put a fire in the y-2 node, with the "flint and steel" item)
4) wait some seconds, the water will boil
5) drop 2 apple (for example) inside the boiling water
6) the water will become in an another color (random color)
7) take your "bowl" item and fill it with the "soup"
8) drink the soup :)

**Comment by ObaniGemini** [comment]
Intuitive :+1:

**Comment by aerozoic** [comment]
Sorry i wasn't clear in my last post. Yes it works with apples. However, it does not work with any of the farming crops (green beans, tomatos, patatos, rhubarb, grapes, etc...)

**Comment by BetterToAutomateTheWorld** [comment]
Maybe it's better to inform @kilbith and let him add support for the farming/farming_redo mod ?
Or we can do it and upstream the code

**Comment by kilbith** [comment]
Le chaudron ne procède pas par support de mods spécifiques, mais par noms d'ingrédients (approche plus flexible).

C'est très simple d'ajouter plus d'ingrédients ici : https://github.com/kilbith/xdecor/blob/master/cooking.lua#L1

Voilà, à vous de voir ça.

**Comment by BetterToAutomateTheWorld** [comment]
Ne serait-il pas mieux d'avoir une liste de filtre plus grande de base sur ton mod ? (qui permettrait de supporter pleinement farming/farming_redo, utilisé d'office dans un grand nombre de serveurs)

**Comment by kilbith** [comment]
J'ai bien peur que cette liste soit vraiment longue si j'ajoutais tous les noms d'ingrédients possibles...

**Comment by Lymkwi** [comment]
Se pourrait-il qu'il y ait un group food commun aux nourritures qui permettrait de les filtrer? Si non, ça pourrait être ajouté.

**Comment by kilbith** [comment]
Non, je crois que j'ai une meilleure idée : vérifier si les items dans le chaudron ont `minetest.item_eat` dans leurs définitions.

**Comment by Lymkwi** [comment]
Oui, cela éviterait d'avoir à unifier les items avec un group. Ça ne doit pas être très compliqué. Le seul problème, c'est que la fonction peut-être redéfinie au démarrage, et si par accident des items ont une version antérieure à la définition, ils ne seront pas comptés.

**Comment by kilbith** [comment]
Bon, je laisse tomber mon idée. J'ai aucun moyen de convertir du code source en string pour vérifier si c'est bien cette fonction qui est appelée (mis à part avec un hack bien moche).

**Comment by Lymkwi** [comment]
> (mis à part avec un hack bien moche)

C'est comme ça que l'on résout les problèmes ici dans ce cas... Je vais voir si je peux faire quelque chose.

**Comment by kilbith** [comment]
Bon j'ai fait ça pour savoir si un item a `minetest.item_eat` dans sa définition : https://github.com/kilbith/xdecor/commit/079e07a4ba450c3b4982167ba453d163c0676b5c

Mais comme je l'ai dit c'est un hack assez moche (conversion de bytecode en string) et on peut pas compter à 100% dessus...

**Comment by Lymkwi** [comment]
Ça semble bon. On va le merger et voir ici sur le serveur ce qu'il en est.

**Comment by aerozoic** [comment]
Now the torch causes the water to boil only for a couple seconds then it stops and repeats. Also using fire under cauldron boils water normally but it will not cook any food, even apples.

**Comment by Lymkwi** [comment]
The cauldron's triggers have been modified and moved many times and during one update I forgot one of them, so if the server is set to that version of xdecor it is constantly turning the cauldron to boil and back to idle.

**Comment by Lymkwi** [comment]
All right, this will solve everything : https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/b99a2b4f21d3b9c278c2d699f6f6e3aa834bf329

**Comment by BetterToAutomateTheWorld** [comment]
I hope, im waiting the next merge (surely this week-end) to confirm this and close the issue

**Comment by aerozoic** [comment]
I still can't get it to cook anything.

**Comment by Lymkwi** [comment]
So apparently, food isn't absorbed anymore.
@Ombridride please, tell me the code has updated correctly..

**Comment by kilbith** [comment]
Pour moi ça a toujours bien fonctionné en passant. Assurez-vous que @cessna151 jette les items dans le chaudron de la bonne manière.

**Comment by BetterToAutomateTheWorld** [comment]
@LeMagnesium All updates are correct in my side

**Comment by Lymkwi** [comment]
> Assurez-vous que @cessna151 jette les items dans le chaudron de la bonne manière.

Moi même, sur le serveur, j'ai essayé de lancer la nourriture dans le chaudron. En local, et sur le serveur Chlorine, tout fonctionnait, mais pas sur le serveur Skyblock : les items n'étaient pas absorbés.

**Comment by BetterToAutomateTheWorld** [comment]
Ils étaient pourtant absorbé jusqu'a récemment...

**Comment by aerozoic** [comment]
Alright, i did some more testing. It works now if i drop two DIFFERENT food items. It will not work if i drop two of the same food items (no i didn't drop a stack of 2).

**Comment by kilbith** [comment]
>  It works now if i drop two DIFFERENT food items.

Yes, it's the way it's meant to work.

**Comment by BetterToAutomateTheWorld** [comment]
Well, this issue is done, thank you for your following kilbith
