### ISSUE TITLE
[report] bugs

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#87]
When i use the report button i get this error: "2016-02-22 22:00:04: ERROR[main]: WARNING: invalid use of label without a size[] element"

Also i do not get reports from other players regardless if i'm online or offline.

**Comment by BetterToAutomateTheWorld** [comment]
@LeMagnesium Can you check it ?
@cessna151 do you have **kick** and **ban** privilege ?

**Comment by aerozoic** [comment]
Confirmed...

>  Privileges of cessna151: interact areas fast irc_admin home ban fly shout kick spawn

**Comment by ghost** [comment]
fix  "invalid use of label without a size[] element" -> https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/dee5b706161fef608cb8c7f67639fbe7b5a4b631

**Comment by aerozoic** [comment]
> Also i do not get reports from other players regardless if i'm online or offline.

Was this fixed?

**Comment by aerozoic** [comment]
@Ombridride Will you please clarify, do you want me to get reports when i'm offline?

**Comment by BetterToAutomateTheWorld** [comment]
Yes i want you to have this report when you're online/offline. You're a moderator it's normal

We need to debug it.

**Comment by ghost** [comment]
fixed https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/9d493dd2bc3d9807adf72f10ecefe6255c833cd3

**Comment by BetterToAutomateTheWorld** [comment]
Thank you very much @crabman77 

Closed the issue
