### ISSUE TITLE
Strange chat message

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#88]
The message appeared today at about 16:40 server time. I checked to make sure, there was no player with that name.

![msg](https://cloud.githubusercontent.com/assets/15715378/13325372/8a4aa946-dbaf-11e5-9742-88444fe1c01d.PNG)

**Comment by BetterToAutomateTheWorld** [comment]
Surely a client problem, it seems your client try to read a non iso(US type character, like éôöië etc...
maybe a sign with this bugged character into it... didn't know much on this bugline...

maybe someone else can give his opinion ?

**Comment by Lymkwi** [comment]
It's any string that your current encoding couldn't decode. There's really nothing to do here since it's purely the engine's fault (more precisely of its way to encore chat messages).

**Comment by ObaniGemini** [comment]
That should be solved in the next version BTW
https://github.com/minetest/minetest/pull/2885

**Comment by Lymkwi** [comment]
This PR fell into oblivion about 8 months ago, there's simply no way it will be merged for the next version.

**Comment by BetterToAutomateTheWorld** [comment]
Well, closed the issue because it's client related, and no server related, we can't do anything...

**Comment by ObaniGemini** [comment]
@LeMagnesium : est31 told me he wanted UTF8 based chat implemented for the next release.
