### ISSUE TITLE
Update [xdecor] mod 

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-skyblock#91]
https://forum.minetest.net/viewtopic.php?f=11&t=12534&view=unread#p208696
https://forum.minetest.net/viewtopic.php?f=11&t=12534&view=unread#p208749

https://github.com/kilbith/xdecor/commits/master

**Comment by Lymkwi** [comment]
I hope it updates correctly.
