### ISSUE TITLE
Doors problem

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-skyblock#92]
Le code de @crabman77 qui faisait que les portes s'ouvraient et ce fermaient par deux a été enlevé et ce n'est donc plus le cas en jeux actuellement, peut-on y ré-ajouter ?

**Comment by ghost** [comment]
Non il n'a jamais été mis, ce sont seulement les portes en 3 nodes qui ont la double ouverture.
Et avec le nouveau système il va falloir le revoir.

**Comment by BetterToAutomateTheWorld** [comment]
Autant pour moi, je pensais que c'était les portes en 2x1 aussi, je laisse le ticket ouvert pour l'ajout de l'ouverture automatique des portes collées en 2x1 et 3x1 avec la nouvelle API donc

**Comment by ghost** [comment]
c'est un système de mesh maintenant, comme les double chest, il y a qu'un node qui interagit, ça va être plus simple car une seule pos à gérer, il faut juste rajouter le code qui check l'orientation pour trouver la 2ème porte et déclencher le callback.

Pour les portes en 3 nodes  il faut refaire les textures puis voir avec @farfadet46 si il peut nous faire un mesh de porte en 3 nodes puis rajouter les check pour le 3ème node.

**Comment by farfadet46** [comment]
oui je peut vous faire le/s mesh/s de porte sans problème ; a vous de me dire ce que vous voulez comme niveau de détails ;)

**Comment by ObaniGemini** [comment]
@farfadet46 : un rectangle de 3 sur 1 avec 4 carrés pour les fenêtres à l'intérieur ^^

**Comment by ghost** [comment]
@Farfadet tu regardes le mesh dans le mod doors et tu ajoute un node, je crois que c'est juste un rectangle de l’épaisseur de la porte et ce sont les textures qui font les détails.

**Comment by farfadet46** [comment]
ok je vais voir ça

@crabman77 peut tu essayer avec ça du coup ?
https://up1.ca/#VvctwBqohEguwfg3Ho3qFA

**Comment by BetterToAutomateTheWorld** [comment]
Avez-vous terminé ce ticket ? je sais que vous travailliez dessus un soir, et le ticket n'a pas été MAJ

**Comment by ghost** [comment]
y a une autre issue ouverte, il faut debug le sand qui tombe sur la porte.

**Comment by BetterToAutomateTheWorld** [comment]
Ouais mais c'est un autre ticket, ce ticket concerne uniquement l'ouverture simultané des portes collés :)

**Comment by BetterToAutomateTheWorld** [comment]
Up, @crabman77 do you still want to do this issue ?

**Comment by ghost** [comment]
Fixed https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/b43afcd2a95989ffae8bcf54d60834bc047e312d

ajout du système ouverture/fermeture des portes collées.

**Comment by BetterToAutomateTheWorld** [comment]
Thank you for your work
