### ISSUE TITLE
[xdecor] mese lamp nodes

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#94]
Mese lamp nodes (nano slabs, micro slabs, etc...) from the worktable don't emit light.

**Comment by BetterToAutomateTheWorld** [comment]
Did you try to left/right "click" it ?

**Comment by Lymkwi** [comment]
This is surely the reason why meselamps shouldn't have been included in the list of cuttable items : xdecor doesn't retrieve the value of "light_source" for the original node.
It didn't before.
https://github.com/MinetestForFun/server-minetestforfun-skyblock/commit/3b3ff36d83f2072409c4e7a6be8b82ac55f42325
