### ISSUE TITLE
Strange IRC error

### ISSUE THREAD

**Issue by aerozoic** [MinetestForFun/server-minetestforfun-skyblock#95]
> 2016-03-15 17:56:11: ERROR[CurlFetchThread]: servers.minetest.net/announce not found (Couldn't resolve host name) (response code 0)
> 2016-03-15 17:58:09: ACTION[ServerThread]: Karluss [???.???.???.???] joins game. 
> 2016-03-15 17:58:09: ACTION[ServerThread]: Karluss joins game. List of players: Karluss
> 2016-03-15 18:01:11: ACTION[ServerThread]: [TimeRegulation] Entering night period : time_speed 90.09009009009
> 2016-03-15 18:11:01: ERROR[ServerThread]: IRC: Error: Disconnected, reconnecting in one minute.
> ...inetestforfun_skyblock/mods/irc_modpack/irc/init.lua:71: Le réseau n'est pas accessible
> stack traceback:
>     [C]: in function 'error'
>     ...estforfun_skyblock/mods/irc_modpack/irc/irc/main.lua:154: in function 'getline'
>     ...estforfun_skyblock/mods/irc_modpack/irc/irc/main.lua:162: in function 'think'
>     ...inetestforfun_skyblock/mods/irc_modpack/irc/init.lua:71: in function <...inetestforfun_skyblock/mods/irc_modpack/irc/init.lua:71>
>     [C]: in function 'xpcall'
>     ...inetestforfun_skyblock/mods/irc_modpack/irc/init.lua:71: in function <...inetestforfun_skyblock/mods/irc_modpack/irc/init.lua:60>
>     (tail call): ?
>     ...ntinbd/mff-skyblock/bin/../builtin/game/register.lua:355: in function <...ntinbd/mff-skyblock/bin/../builtin/game/register.lua:335>
> 2016-03-15 18:12:13: ACTION[ServerThread]: IRC: Connected!

**Comment by Lymkwi** [comment]
> Le réseau n'est pas accessible

'Network is unreachable'. Somehow the server got disconnected from the network. We aren't to blame, it's a normal reaction from irc mod to any IRC error.

**Comment by BetterToAutomateTheWorld** [comment]
Yes, not a problem in my point of view
